### ISSUE TITLE
Optimizing over arrays as parameters

### ISSUE THREAD

**Issue by mcfefa** [robertfeldt/BlackBoxOptim.jl#102]
I want to use BlackBoxOptim to optimize a treatment schedule in an ODE model.  In my ODE model, I have two different treatment schedules to optimize across and I can input an array as each of those two parameters.  I can't input two arrays in a tuple to describe the bounds of the system, I get an error. Other ways that I try to optimize over the treatment schedule, I just get one giant schedule back that doesn't distinguish between treatments. How can I use BBOptim to optimize across my system?

**Comment by robertfeldt** [comment]
Not sure I understand the problem but will try to answer anyway...

If you want to optimize over two arrays you would just "merge" (vcat) them from the perspective of BBO and then "split" into two separate arrays in the fitness function. Example:

```
# Optimize the values of two arrays, one of length 2 and the other of length 3
function fitness(v::Vector{Float64})
v1 = view(v, 1:2)
v2 = view(v, 3:5)
# Dummy/example fitness func, use yours...
sum(v1) - sum(v2.^3)
end
using BlackBoxOptim
r = bboptimize(fitness; SearchRange = (-5.0, 5.0), NumDimensions = 2+3);
best_candidate(r)
```

when I run this I get:

```
julia> best_candidate(r)
5-element Array{Float64,1}:
 -4.99999999991631
 -4.999999998098694
  4.999999999946375
  4.999999999997076
  4.999999999994899
```

which makes sense when minimizing. Hope this helps!
