### ISSUE TITLE
Problematic dependence on Distributions package (?)

### ISSUE THREAD

**Issue by johanbluecreek** [robertfeldt/BlackBoxOptim.jl#104]
I have the following issue:

First: Perform a search and save the result
```
using BlackBoxOptim
res = bboptimize(...)
using JLD2
@save "save_res.jld" res
```
Second: Load the result
```
using BlackBoxOptim
using JLD2
@load "save_res.jld" res
```

This gives me an error that I do not have `Distributions.Cauchy` in the current workspace. As a work-around I use when loading, instead
```
using BlackBoxOptim
using JLD2
using Distributions
@load "save_res.jld" res
```
which works, but in for example Jupyter I get the warning: `WARNING: both Distributions and BlackBoxOptim export "params"; uses of it in module Main must be qualified`.

Perhaps this is more  of an issue for my workflow, but it does appear that BlackBoxOptim depends on Distributions in a way that is not completely smooth.

**Comment by robertfeldt** [comment]
Thanks for this report, Johan. It is strange because we do have "using Distributions" in the main file as well as in the bimodal_cauchy_file.jl where we use the distribution. I'm not sure how JLD2 works so I can't really debug this. If you (or @alyst ?) have any insight please share?

**Comment by robertfeldt** [comment]
Hmm, we only do using Distributions "inside" the BlackBoxOptim module though, maybe JLD2 requires it to be "on the outside"? Seems a bit strange to me though but I guess we can add it to the top-level if this is the preferred way.

**Comment by robertfeldt** [comment]
As an alternative, please try using Julia's built-in serialization. I've mostly used that myself so not much experience with JLD2.

**Comment by alyst** [comment]
I'm not sure why `Cauchy` is not visible to `JLD2`, maybe it's worth clarifying with JLD2 maintainers. Your solution of `using BlackBoxOptim, Distributions` is fine. The warning
> WARNING: both Distributions and BlackBoxOptim export "params"; uses of it in module Main must be qualified.

just means that one has to use either `BlackBoxOptim.params()` or `Distributions.params()` when both packages are loaded. BBO's `params()` is independent from `Distributions` method, so the only way to get rid of the warning is to rename one of the methods; however, both names describe quite well what each method does.

**Comment by johanbluecreek** [comment]
> As an alternative, please try using Julia's built-in serialization. I've mostly used that myself so not much experience with JLD2.

OK. I do not know what this means :-) but I will look into it.

> I'm not sure why Cauchy is not visible to JLD2, maybe it's worth clarifying with JLD2 maintainers. [---]

OK. I should perhaps have looked into JLD2 before coming here... I'll go over there and see what happens. I'll update here when I know something new.

Thanks for all the help and pointer so far.

**Comment by robertfeldt** [comment]
Ok, you can also check here:

https://docs.julialang.org/en/v1/stdlib/Serialization/index.html
