### ISSUE TITLE
optimizing noisy function

### ISSUE THREAD

**Issue by tpapp** [robertfeldt/BlackBoxOptim.jl#112]
I am optimizing a noisy objective (in particular, squared difference between data and simulated moments, in a problem where I can only obtain the latter via stochastic simulation, parameter dimension 15-20).

I wonder how to best go about this using this library. I thought SPSA would be the method of choice (I know little about these things), but it seems to terminate quite early. Is it possible to tune it, or should I go with another method? For SPSA, which reference should I use to understand the parameters, and how can I set them?

My example is too large for an MWE, but with eg a noisy Rosenbrock, a deterministic method outperforms SPSA:
```julia
using BlackBoxOptim
import Random

Random.seed!(1)

function rosenbrock2d_err(x)
  return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2 + randn() * 0.1
end

bboptimize(rosenbrock2d_err; SearchRange = (-5.0, 5.0),
           NumDimensions = 2, Method = :de_rand_1_bin)

bboptimize(rosenbrock2d_err; NumDimensions = 2,
           Method = :simultaneous_perturbation_stochastic_approximation)
```
outputs
```julia
julia> bboptimize(rosenbrock2d_err; SearchRange = (-5.0, 5.0),
                  NumDimensions = 2, Method = :de_rand_1_bin)
Starting optimization with optimizer DiffEvoOpt{FitPopulation{Float64},SimpleSelector,BlackBoxOptim.DiffEvoRandBin{3},RandomBound{RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps

Optimization stopped after 10001 steps and 0.013685941696166992 seconds
Termination reason: Max number of steps (10000) reached
Steps per second = 730749.861575179
Function evals per second = 741417.7427660575
Improvements/step = 0.0581
Total function evaluations = 10147


Best candidate found: [0.968474, 0.938406]

Fitness: -0.348802613

BlackBoxOptim.OptimizationResults("de_rand_1_bin", "Max number of steps (10000) reached", 10001, 1.547554341285924e9, 0.013685941696166992, DictChain{Symbol,Any}[DictChain{Symbol,Any}[Dict{Symbol,Any}(:RngSeed=>350257,:NumDimensions=>2,:SearchRange=>(-5.0, 5.0),:Method=>:de_rand_1_bin,:MaxSteps=>10000),Dict{Symbol,Any}()],Dict{Symbol,Any}(:FitnessScheme=>ScalarFitnessScheme{true}(),:NumDimensions=>:NotSpecified,:PopulationSize=>50,:MaxTime=>0.0,:SearchRange=>(-1.0, 1.0),:Method=>:adaptive_de_rand_1_bin_radiuslimited,:MaxNumStepsWithoutFuncEvals=>100,:RngSeed=>1234,:MaxFuncEvals=>0,:SaveTrace=>false…)], 10147, ScalarFitnessScheme{true}(), BlackBoxOptim.TopListArchiveOutput{Float64,Array{Float64,1}}(-0.34880261331342, [0.968474, 0.938406]), BlackBoxOptim.PopulationOptimizerOutput{FitPopulation{Float64}}(FitPopulation{Float64}([0.994776 0.948154 … 0.944123 1.12178; 0.974077 0.896647 … 0.886015 1.26189], NaN, [-0.23279, -0.251039, -0.207235, -0.211513, -0.201575, -0.277171, -0.242012, -0.269654, -0.217689, -0.183884  …  -0.268284, -0.23104, -0.208383, -0.238084, -0.168211, -0.237212, -0.276101, -0.18603, -0.26141, -0.233179], 0, BlackBoxOptim.Candidate{Float64}[Candidate{Float64}([1.07862, 1.16507], 29, -0.202317, DiffEvoRandBin{3}(0.7, 0.6), 0), Candidate{Float64}([0.87758, 1.16507], 29, 15.6013, DiffEvoRandBin{3}(0.7, 0.6), 0)])))

julia> bboptimize(rosenbrock2d_err; NumDimensions = 2,
                  Method = :simultaneous_perturbation_stochastic_approximation)
Starting optimization with optimizer SPSA2 (Simultaneous Perturbation Stochastic Approximation, 1st order, 2 samples)
0.00 secs, 0 evals, 0 steps

Optimization stopped after 10001 steps and 0.042726993560791016 seconds
Termination reason: Max number of steps (10000) reached
Steps per second = 234067.4867697115
Function evals per second = 468134.973539423
Improvements/step = 0.0
Total function evaluations = 20002


Best candidate found: [1.57449, 2.46637]

Fitness: 0.147406439

BlackBoxOptim.OptimizationResults("simultaneous_perturbation_stochastic_approximation", "Max number of steps (10000) reached", 10001, 1.547554341321574e9, 0.042726993560791016, DictChain{Symbol,Any}[DictChain{Symbol,Any}[Dict{Symbol,Any}(:RngSeed=>63230,:NumDimensions=>2,:Method=>:simultaneous_perturbation_stochastic_approximation,:MaxSteps=>10000),Dict{Symbol,Any}()],Dict{Symbol,Any}(:FitnessScheme=>ScalarFitnessScheme{true}(),:NumDimensions=>:NotSpecified,:PopulationSize=>50,:MaxTime=>0.0,:SearchRange=>(-1.0, 1.0),:Method=>:adaptive_de_rand_1_bin_radiuslimited,:MaxNumStepsWithoutFuncEvals=>100,:RngSeed=>1234,:MaxFuncEvals=>0,:SaveTrace=>false…)], 20002, ScalarFitnessScheme{true}(), BlackBoxOptim.TopListArchiveOutput{Float64,Array{Float64,1}}(0.14740643850952137, [1.57449, 2.46637]), BlackBoxOptim.DummyMethodOutput())
```

**Comment by robertfeldt** [comment]
Interesting problem. I  haven't much experience from optimizing noisy objectives myself so cannot really give a deep answer for if BBO is the way to go but here are some ideas for what you can try:

1. Run for longer by specifying a longer MaxTime. Over time the noise/flukes should have less influence!? Example running for 5 seconds:

```julia
Random.seed!(1)
bboptimize(rosenbrock2d_err; SearchRange = (-5.0, 5.0),
                  NumDimensions = 2, Method = :de_rand_1_bin, MaxTime = 5.0)
# Best candidate found: [0.978182, 0.960822]
# Fitness: -0.454954057
```

However, the main problem with noisy objectives is probably that you can have an early "fluke" evaluation that then makes it hard to "back out from" during the rest of the optimization. I guess one way to get around it (if you can afford it) would be:

2. Multiple executions per candidate and return the median fitness

This should "smoothen out" the errors somewhat but that of course depends on how costly it is to evaluate the objective function and how large the noise (SNR) really is. Example:

```julia
NumReps = 3 # Num calls to orig obj func
using StatsBase: median
function median_obj_func(x::Vector{Float64})
    median(Float64[rosenbrock2d_err(x) for _ in 1:NumReps])
end

bboptimize(median_obj_func; SearchRange = (-5.0, 5.0),
           NumDimensions = 2, Method = :de_rand_1_bin, MaxTime = 5.0)
# Best candidate found: [1.01914, 1.04379]
# Fitness: -0.317381824
# Not clear it is really better but could need more time now since more reps etc so could be workable solution if experimenting with it.
```

A better solution might be to re-evaluation adaptively, i.e. save the current best candidate, and re-evaluate and compare to it only for candidates that are getting better. Problem here is to select which fitness to return back when not re-evaluating since this might mess up the gradients.

Is any of this helpful for your case?

**Comment by robertfeldt** [comment]
Ah, maybe I misunderstood. If you asked for the paper that inspired the SPSA2 implementation in BBO this is the paper:

Spall, James C. "Adaptive stochastic approximation by the simultaneous perturbation method." IEEE transactions on automatic control 45.10 (2000): 1839-1853.
https://www.jhuapl.edu/spsa/PDF-SPSA/Spall_TAC00.pdf

Long time ago since I read and implemented that and it has never really given good results so I haven't used or tuned it much. The parameters in the code are:

```julia
const SPSADefaultParameters = ParamsDict(
    :Alpha => 0.602,  # The optimal value is 1.0 but values down to 0.602 often can give faster convergence
    :Gamma => 0.101,  # The optimal value is 1/6 but values down to 0.101 often can give faster convergence
    :a     => 0.0017,
    :c     => 1.9, # Recommendation is value 1.9 but that assumes noisy function, otherwise should be low
    :A     => 10
)
```

and I assume I got the default values from the paper. But I'm not sure. ;)

**Comment by robertfeldt** [comment]
Hmm, the SPSA2 is performing so badly that I almost doubt I have implemented it correctly. If you dig deeper on this it would be great if you find some alternative implementation of SPSA2 that we can differential test against. Or if you just review the code. It is very short. ;)

**Comment by robertfeldt** [comment]
In the Spall paper it does say that the value of parameter A should be set to 5-10% of the number of iterations of the algorithm that is expected so the current default of A=10 seems sub-optimal. ;) However, I think the main problem seems to be that the current BBO SPSA2 implementation does not respect the search space bounds. At least some runs I did didn't ensure the best candidate was fully in the search space. So it seems the current SPSA2 implementation is not to be trusted. Sorry.

**Comment by tpapp** [comment]
Thanks for the advice. Indeed I was looking for the paper — my understanding is that some tuning is required. I will look into this and the algorithm, but it will take some time since this is an unfamiliar field for me.
