### ISSUE TITLE
Example: ODE Lorenz Attractor, small bugs

### ISSUE THREAD

**Issue by finmod** [robertfeldt/BlackBoxOptim.jl#116]
@robertfeldt Thank you for updating this example in a direction that I welcome. I failed to notice last August.

Just want to flag that in Julia 1.0.3 the syntax for collect has changed to: 

t  = collect(range(0,stop=100,length=100001)) and

t_Xiang2015 = collect(range(0,stop=3,length=301)) 

But I have a problem with:

origstates = calc_state_vectors(real_params, lorentz_equations, r0, t)
origstates_Xiang2015 = calc_state_vectors(real_params, lorentz_equations, r0, t_Xiang2015)

function subsample(origstates::Array{Float64, 2}, times::Vector{Float64}, lenratio = 0.25)
    @assert size(origstates, 2) == length(times)
    N = length(times)
    stopidx = round(Int, lenratio*N)
    indexes = 1:stopidx
    return origstates[:, indexes], times[indexes]
end

that gives:

MethodError: no method matching Array(::Type{Float64}, ::Int64, ::Int64)
Closest candidates are:
  Array(!Matched::LinearAlgebra.UniformScaling, ::Integer, ::Integer) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\LinearAlgebra\src\uniformscaling.jl:330

Stacktrace:
 [1] #calc_state_vectors#4(::Nothing, ::Function, ::Array{Float64,1}, ::typeof(lorentz_equations), ::Array{Float64,1}, ::Array{Float64,1}) at .\In[14]:7
 [2] calc_state_vectors(::Array{Float64,1}, ::Function, ::Array{Float64,1}, ::Array{Float64,1}) at .\In[14]:5
 [3] top-level scope at In[16]:1

**Comment by alyst** [comment]
Thanks for the notice. It seems L50 of `ode_lorenz_attractor.jl` needs updating.
I'll take care of this, but in future pls feel free to submit PR with the fixes, as it would speed up the process.
