### ISSUE TITLE
Optimization crashed when finds NaN or Inf

### ISSUE THREAD

**Issue by ayadlin** [robertfeldt/BlackBoxOptim.jl#122]
My issue is similar to dxnes chkfinite bug for README compare_optimizers example #93
When i try to run (not compare) an optimization for parameter stimation on my DAE system I get

Starting optimization with optimizer XNESOpt{Float64,RandomBound{RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps
sigma=1.0 |trace(ln_B)|=NaN
ArgumentError: matrix contains Infs or NaNs

Is there a solution to for the optimization to continue?

Looking deeper, I think this is due to the fact that for some of my parameters the lower and upper bound are equal (ie I'm trying to fix the value of the parameter - is there a way to do this so I can fix arbitrary parameter using the bound regions?)

Thanks

A

**Comment by robertfeldt** [comment]
If there are parameters you don't need to optimize just add/fix them in the fitness function instead. Best would be to optimize only the parameters that need to be optimized and then add the fixed values in the fitness function before calling the old/original fitness function. Would this help you in this case?

**Comment by ayadlin** [comment]
Thanks for the super quick response!

What you are suggesting could definitively work, but in my case it will transform one DAE system into multiple ones.

The parameters I am trying to fit are those that define my differential equation model function -  The only way I can think to fix them is just to replace them by a number instead of a variable at this stage (make my DAE function take 8 parameters instead of 20), but that would mean having many semi-identical DAE functions with different parameters fixed, depending on which parameters I have experimental data for in different studies. That would be less than ideal, but definitively possible.
 
In the ideal case, because it would allow the most flexibility when defining my or any DAE/ODE system, would be for fixed parameters being defined at the optimization stage, by defining upper_bound = lower_bound for that parameter and removing that parameter from the dimensional search (ie if i have 36 parameters and 20 are fixed dims =18). That way defining one DAE function allows to fit any subset of parameters to the data, while the rest remain fixed.  Does this makes sense to you?

I am currently working on 12 projects (that may expand as high as 30) that can all be modeled by the same DAE system, but for which have different set of measured parameters so having a way to fix parameters at the optimization stage would allow me to use a unique DAE system to fit the reminder params in each case without having to write 12 different DAE systems.

I am not sure if this is an improvement that it is worth your time -
For the time being I am tricking the system, by giving very small intervals to the parameters i want fixed ie upper = 1.00001*lower. This works great for xnes and selected_nes, not at al as you might expect fro dxnes.


Either way I do appreciate your quick response to my issue :)

Take care,

A

**Comment by robertfeldt** [comment]
Before we think about possible fixes I just want to really understand your situation.

I might have misunderstood but to me it sounds like you don't need to create multiple different DAE systems, you just need to wrap the original (DAE) fitness function in different ways for the different optimization functions. Example below:

```julia
# Original DAE system fitness func, say it takes a 30 param vector
origfitness(v) = ...your code here...
Dims = 30

# In specific opt problem A there are two vars (at position 2 and 7) with fixed values 3.14 and 5.7, respectively
problemAfixed = [(2, 3.14), (7, 5.7)]

# General func to fix certain values at given positions in a vector
function fixvalues(vs, fixspec, dims)
    newvs = zeros(Float64, dims)
    vsidx = fixidx = 1
    for i in 1:dims
        if (fixidx <= length(fixspec) && i == fixspec[fixidx][1]
            newvs[i] = fixspec[fixidx][1]
            fixidx += 1
        else
            newvs[i] = vs[vsidx]
            vsidx += 1
        end
    end
    newvs
end

# Fitness func for problem A is now
fitnessA(vs) = origfitness(fixvalues(vs, problemAfixed, Dims))

# Now we can call bboptim as usual and optimizing a 30-2=28 value vector with for fitnessA.
# fixvalues(best_candidate(result), problemAfixed, Dims)) then is our best solution to the general DAE problem.

# For other variants just use a different fixspec and num dimensions.
```

Would this be useful?

**Comment by ayadlin** [comment]
Thanks so much -
Sorry it took me so long to reply - lots of sick ppl at home.
i think so, I am relatively new to Julia, so let me see if I understand the logic -

fixvalues in this case would replace the value of parameter 2 by 3.14 and 7 by 5.7
but would it do this before or during the optimization?
Do I need to run bbopt with 30 open variables to get result and then just change the numbers for param 2 and 7 or do I call

```

#Let' say I have 3 variables as before and variables 1 and 3 are fixed 
problemAfixed = [(1, 10.0), (3, 8/3)]
lower=Float64.([0, 0, 0])
upper=Float64.([20, 30, 10])
dims=3

# Now we can call bboptim as usual and optimizing a 3-2=1 value vector with for fitnessA.
# is this how you'd run the optimization ?
fitnessA(vs) = origfitness(fixvalues(vs, problemAfixed, dims))
opt3 = bbsetup(fitnessA; Method=:separable_nes, SearchRange = (lower[2],upper[2]),
               NumDimensions = 1, MaxFuncEvals = 5000)
bb3=bboptimize(opt3);

# The code above would optimize parameter 2 while keeping 1 and 3 always at the assign value 

# This last line just take the optimized vector and build the parameters with the fixed values
fixvalues(best_candidate(bb3, problemAfixed,dims)
```

am I correct?


Thanks,

A

**Comment by ayadlin** [comment]
Also, i ight be worng, but in your function I think there is a typo- it should be

newvs[i] = fixspec[fixidx][2] not [1]

```
# Original DAE system fitness func, say it takes a 30 param vector
origfitness(v) = ...your code here...
Dims = 30

# In specific opt problem A there are two vars (at position 2 and 7) with fixed values 3.14 and 5.7, respectively
problemAfixed = [(2, 3.14), (7, 5.7)]

# General func to fix certain values at given positions in a vector
function fixvalues(vs, fixspec, dims)
    newvs = zeros(Float64, dims)
    vsidx = fixidx = 1
    for i in 1:dims
        if (fixidx <= length(fixspec) && i == fixspec[fixidx][1]
            newvs[i] = fixspec[fixidx][2]
            fixidx += 1
        else
            newvs[i] = vs[vsidx]
            vsidx += 1
        end
    end
    newvs
end

```

**Comment by robertfeldt** [comment]
Yes, it should be `fixspec[fixidx][2]` to set the fixed value as you say. Sorry for the bug, I was in a hurry.

Yes, you should not optimize with the values that are fixed. So if your problem has N predictors/variables and M fixed values you should optimize a N-M vector of (the remaining) variables.

Hope this helps!

**Comment by robertfeldt** [comment]
I also noted a missing paren in your final line of code, it should be:

````
fixvalues(best_candidate(bb3), problemAfixed,dims)
```

**Comment by ayadlin** [comment]
Thanks so much.
This was super helpful!
Let me know if you’d like me to share the final function that fits parameters to generic DAE.

I’ll be happy to, but don’t want to spam you.

Take care,

A

**Comment by robertfeldt** [comment]
Glad it helped!

If you can write a small example I can add it to the examples dir, thanks.

**Comment by ayadlin** [comment]
Thanks again 
Will do.
Take care-

A
