### ISSUE TITLE
Callback fails to run

### ISSUE THREAD

**Issue by JonasIsensee** [robertfeldt/BlackBoxOptim.jl#123]
Hi,
I'm on julia 1.0.3 and BlackBoxOptim v0.4.0
and the `CallBack` interface is not working for me.

I tried executing your example from 
https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/save_fitness_progress_via_callback_function.jl

but it just returns an empty list. (In a clean julia session)
Any ideas?

**Comment by robertfeldt** [comment]
Hmm, can you please try the same thing on latest master of the git repo? Might be some updates on there are needed.

**Comment by JonasIsensee** [comment]
This works! Thank you for the quick reply.
Please consider tagging a new minor version.
