### ISSUE TITLE
New release + JuliaRegistrator + JuliaTagBot

### ISSUE THREAD

**Issue by alyst** [robertfeldt/BlackBoxOptim.jl#127]
It's been a while since the last version (0.4.0) was released.
There are some new features added to master after 0.4.0 (#107, #111) and some bugfixes.

Also, julia ecosystem has switched to using Project.toml instead of REQUIRES and to the new GitHub apps (https://github.com/JuliaRegistries/Registrator.jl and https://github.com/apps/julia-tagbot) that automate the release process.
It would be nice to update BBO to use this too.

**Comment by alyst** [comment]
I'll try to submit the PR replacing *REQUIRE* with *Project.toml* (via [gen_project.jl](https://github.com/JuliaLang/Pkg.jl/blob/master/bin/gen_project.jl)) within a few days.

**Comment by robertfeldt** [comment]
Yes, I'm definitely in support of this and did hook up Registrator.jl some time back. However, if you can help out with additional steps that's appreciated; I'm currently on vacation with bad connectivity (for a few more weeks).

**Comment by alyst** [comment]
@robertfeldt Great! Have you also enabled TagBot? (It complements Registrator by automatically generating git tags and github releases once JuliaRegistry accepts the new package version)

**Comment by robertfeldt** [comment]
TagBot is installed. Maybe it is the Registrator setup that is not complete. If you can check which changes are needed to the repo I can then try to set things up correctly. Thanks!

**Comment by robertfeldt** [comment]
Both Registrator and TagBot enabled on BBO repo.
