### ISSUE TITLE
More Agressive Algorithm

### ISSUE THREAD

**Issue by castrovjm** [robertfeldt/BlackBoxOptim.jl#134]
Hi, sorry for opening this weird thread.

I am minimizing a very noisy objective function using :dxnes  and I am specifying a large domain for all the variables. Somehow, after a small number steps (approx. 25) the algorithm gets "stuck" and starts evaluating points that are very close to each other. 

Is there a way to modulate how agressive is the algorithm in searching for the global optimum?

**Comment by robertfeldt** [comment]
Hmm, some of its parameters should/could be relevant for this but I honestly don't remember the details of the NES algorithms. Have you tried one of the adaptive evolutionary algorithms for this problem? They tend to be fairly robust.
