### ISSUE TITLE
Is it possible to add a progress bar for estimating time it would took for the optimization

### ISSUE THREAD

**Issue by danielchen26** [robertfeldt/BlackBoxOptim.jl#135]

**Comment by robertfeldt** [comment]
Maybe we could use [ProgressMeter.jl](https://github.com/timholy/ProgressMeter.jl)? Other ideas for how to do it?

**Comment by jpsamaroo** [comment]
ProgressMeter.jl sounds like a good idea (that's what MLJ uses when doing things like grid search, and it looks pretty nice), along with a separate keyword argument to `bboptimize` like `ShowProgress = true/false`.

**Comment by robertfeldt** [comment]
Do you see a big benefit to having this as part of the standard API compared to just show people how to invoke ProgressMeter in a callback function using the existing callback function API? I haven't tried it directly but should be fairly straightforward if a bit clunky.

**Comment by jpsamaroo** [comment]
Not necessarily, an example of how to do this from the user side would be perfectly suitable. I just didn't consider that very obvious option :)

**Comment by robertfeldt** [comment]
Ok, I added an example here now:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/progressmeter_during_optimization.jl

Please check if this works on your side. Looks good for me on Julia 1.2. Comments welcome.

**Comment by danielchen26** [comment]
I just tried the example. It looks good

**Comment by robertfeldt** [comment]
Note that this is in no way perfect since it takes quite some time when bboptim is called until optimization actually starts. OTOH, ProgressMeter doesn't seem to start printing the progress bar until the first call to update! so maybe fine anyway.

**Comment by robertfeldt** [comment]
Thanks @danielchen26. If @jpsamaroo also thinks this is ok I'll close this issue.
