### ISSUE TITLE
Options structure setup

### ISSUE THREAD

**Issue by lnacquaroli** [robertfeldt/BlackBoxOptim.jl#139]
I was trying to find out some function to build a general structure for the options like `bbsetup` but without the objective function, just the options of the algorithms and method. Basically, what I am trying to do is:

```julia
options = bboOptions(
   SearchRange = (-5.0, 5.0),
   NumDimensions = 2,
   Method=:adaptive_de_rand_1_bin_radiuslimited,
)
res = bboptimize(rosenbrock2d(x); options)
```

where `bboOptions` is the function I'm looking for.

Is there any functionality that supports that?

**Comment by robertfeldt** [comment]
You can just splat in the keyword arguments from a dict?

```julia
options = Dict(
          :SearchRange => (-5.0, 5.0),
          :NumDimensions => 2,
          :Method => :adaptive_de_rand_1_bin_radiuslimited
       )
res = bboptimize(rosenbrock2d(x); options...)
```

**Comment by lnacquaroli** [comment]
Yeah, the splat in did work for both Dict and Tuple. Thanks for you answer.
