### ISSUE TITLE
key arg for stopping criterion

### ISSUE THREAD

**Issue by WT215** [robertfeldt/BlackBoxOptim.jl#140]
Hi,

Thank you for this wonderful package!

May I ask apart from the argument `MaxFuncEvals`, is there another argument which allows me to make the optimization stop at some point: for example, let user to set up a threshold such that when the fitness does not change a lot within that threshold, the optimization stops. This may speed up the optimization (though we may just get stuck in local minimum).

Thanks a lot!

**Comment by WT215** [comment]
I got results like the following. I wounder if it is possible to stop optimization if the change of fitness is very small; Or if the change is very small, let optimizer try another parameter which is far away from the currently evaluated ones. 
`
0.00 secs, 0 evals, 0 steps
1.34 secs, 2 evals, 1 steps, improv/step: 1.000 (last = 1.0000), fitness=6684.157666918
2.65 secs, 4 evals, 2 steps, improv/step: 1.000 (last = 1.0000), fitness=1108.832536479
3.96 secs, 6 evals, 3 steps, improv/step: 1.000 (last = 1.0000), fitness=1108.832536479
5.25 secs, 8 evals, 4 steps, improv/step: 1.000 (last = 1.0000), fitness=945.508906957
6.58 secs, 10 evals, 5 steps, improv/step: 0.800 (last = 0.0000), fitness=945.508906957
7.91 secs, 12 evals, 6 steps, improv/step: 0.833 (last = 1.0000), fitness=945.508906957
9.24 secs, 14 evals, 7 steps, improv/step: 0.714 (last = 0.0000), fitness=843.934437840
9.96 secs, 15 evals, 8 steps, improv/step: 0.625 (last = 0.0000), fitness=843.934437840
11.39 secs, 17 evals, 9 steps, improv/step: 0.556 (last = 0.0000), fitness=843.934437840
12.77 secs, 19 evals, 10 steps, improv/step: 0.500 (last = 0.0000), fitness=843.934437840
14.22 secs, 21 evals, 11 steps, improv/step: 0.455 (last = 0.0000), fitness=843.934437840
15.60 secs, 23 evals, 12 steps, improv/step: 0.417 (last = 0.0000), fitness=843.934437840
17.06 secs, 25 evals, 13 steps, improv/step: 0.462 (last = 1.0000), fitness=843.934437840
18.42 secs, 27 evals, 14 steps, improv/step: 0.429 (last = 0.0000), fitness=843.934437840
19.16 secs, 28 evals, 15 steps, improv/step: 0.400 (last = 0.0000), fitness=843.934437840
20.55 secs, 30 evals, 16 steps, improv/step: 0.438 (last = 1.0000), fitness=843.934437840
21.98 secs, 32 evals, 17 steps, improv/step: 0.471 (last = 1.0000), fitness=843.934437840
23.43 secs, 34 evals, 18 steps, improv/step: 0.500 (last = 1.0000), fitness=843.934437840
24.14 secs, 35 evals, 19 steps, improv/step: 0.474 (last = 0.0000), fitness=843.934437840
25.64 secs, 37 evals, 20 steps, improv/step: 0.450 (last = 0.0000), fitness=843.934437840
26.37 secs, 38 evals, 21 steps, improv/step: 0.429 (last = 0.0000), fitness=843.934437840
27.74 secs, 40 evals, 22 steps, improv/step: 0.409 (last = 0.0000), fitness=843.934437840
29.22 secs, 42 evals, 23 steps, improv/step: 0.391 (last = 0.0000), fitness=843.934437840
30.67 secs, 44 evals, 24 steps, improv/step: 0.417 (last = 1.0000), fitness=843.934437840
31.39 secs, 45 evals, 25 steps, improv/step: 0.400 (last = 0.0000), fitness=843.934437840
32.12 secs, 46 evals, 26 steps, improv/step: 0.385 (last = 0.0000), fitness=843.934437840
33.54 secs, 48 evals, 27 steps, improv/step: 0.407 (last = 1.0000), fitness=843.934437840
34.98 secs, 50 evals, 28 steps, improv/step: 0.429 (last = 1.0000), fitness=843.934437840
36.59 secs, 52 evals, 29 steps, improv/step: 0.414 (last = 0.0000), fitness=843.934437840
37.27 secs, 53 evals, 30 steps, improv/step: 0.433 (last = 1.0000), fitness=843.934437840
37.97 secs, 54 evals, 31 steps, improv/step: 0.419 (last = 0.0000), fitness=843.934437840
39.37 secs, 56 evals, 32 steps, improv/step: 0.438 (last = 1.0000), fitness=843.934437840
40.07 secs, 57 evals, 33 steps, improv/step: 0.455 (last = 1.0000), fitness=843.934437840
40.77 secs, 58 evals, 34 steps, improv/step: 0.471 (last = 1.0000), fitness=843.934437840
42.17 secs, 60 evals, 35 steps, improv/step: 0.486 (last = 1.0000), fitness=843.934437840
43.67 secs, 62 evals, 36 steps, improv/step: 0.500 (last = 1.0000), fitness=843.934437840
45.05 secs, 64 evals, 37 steps, improv/step: 0.514 (last = 1.0000), fitness=843.934437840
45.81 secs, 65 evals, 38 steps, improv/step: 0.500 (last = 0.0000), fitness=843.934437840
47.29 secs, 67 evals, 39 steps, improv/step: 0.487 (last = 0.0000), fitness=843.934437840
48.72 secs, 69 evals, 40 steps, improv/step: 0.475 (last = 0.0000), fitness=843.934437840
50.15 secs, 71 evals, 41 steps, improv/step: 0.488 (last = 1.0000), fitness=843.934437840
50.86 secs, 72 evals, 42 steps, improv/step: 0.476 (last = 0.0000), fitness=843.934437840
52.26 secs, 74 evals, 43 steps, improv/step: 0.488 (last = 1.0000), fitness=843.934437840
53.03 secs, 75 evals, 44 steps, improv/step: 0.477 (last = 0.0000), fitness=843.934437840
53.72 secs, 76 evals, 45 steps, improv/step: 0.467 (last = 0.0000), fitness=843.934437840
54.47 secs, 77 evals, 46 steps, improv/step: 0.457 (last = 0.0000), fitness=843.934437840
55.91 secs, 79 evals, 47 steps, improv/step: 0.468 (last = 1.0000), fitness=843.934437840
57.41 secs, 81 evals, 48 steps, improv/step: 0.458 (last = 0.0000), fitness=843.934437840
58.13 secs, 82 evals, 49 steps, improv/step: 0.449 (last = 0.0000), fitness=843.934437840
59.55 secs, 84 evals, 50 steps, improv/step: 0.460 (last = 1.0000), fitness=843.934437840
60.26 secs, 85 evals, 51 steps, improv/step: 0.471 (last = 1.0000), fitness=829.096911826
60.97 secs, 86 evals, 52 steps, improv/step: 0.462 (last = 0.0000), fitness=829.096911826
62.35 secs, 88 evals, 53 steps, improv/step: 0.453 (last = 0.0000), fitness=808.898874525
63.75 secs, 90 evals, 54 steps, improv/step: 0.463 (last = 1.0000), fitness=808.898874525
65.19 secs, 92 evals, 55 steps, improv/step: 0.455 (last = 0.0000), fitness=808.898874525
66.60 secs, 94 evals, 56 steps, improv/step: 0.464 (last = 1.0000), fitness=808.898874525
68.03 secs, 96 evals, 57 steps, improv/step: 0.456 (last = 0.0000), fitness=808.898874525
68.74 secs, 97 evals, 58 steps, improv/step: 0.448 (last = 0.0000), fitness=808.898874525
69.45 secs, 98 evals, 59 steps, improv/step: 0.458 (last = 1.0000), fitness=808.898874525
70.15 secs, 99 evals, 60 steps, improv/step: 0.450 (last = 0.0000), fitness=808.898874525
71.60 secs, 101 evals, 61 steps, improv/step: 0.459 (last = 1.0000), fitness=808.898874525
72.31 secs, 102 evals, 62 steps, improv/step: 0.468 (last = 1.0000), fitness=808.898874525
73.73 secs, 104 evals, 63 steps, improv/step: 0.460 (last = 0.0000), fitness=808.898874525
74.46 secs, 105 evals, 64 steps, improv/step: 0.469 (last = 1.0000), fitness=808.898874525
75.92 secs, 107 evals, 65 steps, improv/step: 0.477 (last = 1.0000), fitness=808.898874525
77.33 secs, 109 evals, 66 steps, improv/step: 0.470 (last = 0.0000), fitness=808.898874525
78.03 secs, 110 evals, 67 steps, improv/step: 0.463 (last = 0.0000), fitness=808.898874525
79.48 secs, 112 evals, 68 steps, improv/step: 0.456 (last = 0.0000), fitness=808.898874525
80.19 secs, 113 evals, 69 steps, improv/step: 0.449 (last = 0.0000), fitness=808.898874525
`

**Comment by robertfeldt** [comment]
Thanks!

Documentation is scarce but these params are your friend:

```     
:MaxTime        => 0.0,
    :MaxFuncEvals   => 0,
    :MaxSteps       => 10000,
    :MaxStepsWithoutProgress => 10000,
    :MinDeltaFitnessTolerance => 1e-50,
    :FitnessTolerance => 1e-8,

    :MaxNumStepsWithoutFuncEvals => 100,
```

But this is not as tested as it should be. Please try and report back and we might need to debug...

**Comment by WT215** [comment]
@robertfeldt Great! thanks a lot!
