### ISSUE TITLE
Can I know the number of evaluations?

### ISSUE THREAD

**Issue by zxjroger** [robertfeldt/BlackBoxOptim.jl#144]
Hi, thank you for such an amazing package. I have some simple questions.
1. Can I get the number of evaluations? Is it BlackBoxOptim.f_calls(res) or num_func_evals(res)? What about number of iterations?
2. Is there a quick way to get the value of objective function?
3. When I set fitness tolerance, is it `ftol = 1e-5` or `FitnessTolerance = 1e-8`?
Thank you again.

**Comment by robertfeldt** [comment]
Thanks for your feedback.

1. BlackBoxOptim.num_func_evals can give the number of function evaluations. See for example: https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/save_fitness_progress_via_callback_function.jl

2. Not fully sure what you mean here if you mean for the returned object then ´best_fitness´can be used and example is on the README page. Do you mean something lese?

3. ´FitnessTolerance´ can be used. It is not super well tested so please get back to me if not behaves as you want.

**Comment by zxjroger** [comment]
Thank you for your answer. For point 2, I previously thought "best_fitness" will return the smallest difference between two evaluations of objective functions. What I mean by value of objective function is simply the minimized value of the function as we plug in the solution from "best_candidate". My bad.

**Comment by robertfeldt** [comment]
Ok, sounds like best_fitness is what you are after. Ok, thanks, closing this issue.
