### ISSUE TITLE
Change API to be more in line with Optim.jl and/or JumP.jl

### ISSUE THREAD

**Issue by robertfeldt** [robertfeldt/BlackBoxOptim.jl#145]
Proposal based on a Slack discussion but idea is to make it more like Optim.jl to make it easier to switch between them. When doing this we also should consider adding an interface so we can be back-end to JuMP.jl. We need to check on the new interface design they have their, replacing MathProgBase (old one). This is a thread for discussing a possible new design... Any input @alyst?

**Comment by alyst** [comment]
I'm totally for interoperability. It's just that it's been a long time since I looked into *Optim.jl* interface (at that time I had a feeling that adjustments have to be done on both sides), so I don't have a clear vision on what has to be done.
But as soon as there would be some draft plans, I will be happy to give feedback.

**Comment by robertfeldt** [comment]
Yeah, I'll play some more with Optim.jl and see pros and cons. I want to take BlackBoxOptim more into optimization as well as exploration (QualityDiversity) algorithms so not sure it makes sense to merge efforts with them though. Also want to better support optimization of other things than float64 vectors. Another area of dev would be GUIs/frontends since for more complex algs we need ways to interact with the optimization runs (there is a new example of how this can be done in master, see examples subdir for an example).

**Comment by robertfeldt** [comment]
Actually, I missed checking in the example file yesterday... ;) Here it is now:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/vega_lite_fitness_graph_frontend.jl

This is very basic for now but maybe a starting point for more advanced front-ends.
