### ISSUE TITLE
strftime not define opt_controller.jl:362

### ISSUE THREAD

**Issue by Fmaeng** [robertfeldt/BlackBoxOptim.jl#149]
I got an error message when I tried to save optimization result:

This is the original optimization code.

------------------- 
opt1=bbsetup(functionAR1; Method=:dxnes,
 SearchRange = [(-5.0, 5.0), (0.1, 0.99),(0.1, 2.0)],
 lambda = 50, MaxFuncEvals=10, SaveTrace = true,
 SaveFitnessTraceToCsv = true,
 SaveParameters = true)

el1 = @elapsed res1 = bboptimize(opt1)
cand1 = best_candidate(res1)
fit1  = best_fitness(res1)

------------------------
Basically I set **SaveTrace = true,  SaveFitnessTraceToCsv = true,  SaveParameters = true** to obtain the optimization process results, and I got error message below: 

LoadError: UndefVarError: strftime not defined
in expression starting at untitled-ac9baa1509b4e4ac68e7c1d8ef6ff215:78
write_result(::BlackBoxOptim.OptRunController{BlackBoxOptim.DXNESOpt{Float64,RandomBound{ContinuousRectSearchSpace}},BlackBoxOptim.ProblemEvaluator{Float64,Float64,TopListArchive{Float64,ScalarFitnessScheme{true}},FunctionBasedProblem{typeof(functionAR1),ScalarFitnessScheme{true},ContinuousRectSearchSpace,Nothing}}}, ::String) at opt_controller.jl:363
write_result(::BlackBoxOptim.OptRunController{BlackBoxOptim.DXNESOpt{Float64,RandomBound{ContinuousRectSearchSpace}},BlackBoxOptim.ProblemEvaluator{Float64,Float64,TopListArchive{Float64,ScalarFitnessScheme{true}},FunctionBasedProblem{typeof(functionAR1),ScalarFitnessScheme{true},ContinuousRectSearchSpace,Nothing}}}) at opt_controller.jl:362
run!(::BlackBoxOptim.OptController{BlackBoxOptim.DXNESOpt{Float64,RandomBound{ContinuousRectSearchSpace}},FunctionBasedProblem{typeof(functionAR1),ScalarFitnessScheme{true},ContinuousRectSearchSpace,Nothing}}) at opt_controller.jl:464
#bboptimize#119 at bboptimize.jl:66 [inlined]
bboptimize(::BlackBoxOptim.OptController{BlackBoxOptim.DXNESOpt{Float64,RandomBound{ContinuousRectSearchSpace}},FunctionBasedProblem{typeof(functionAR1),ScalarFitnessScheme{true},ContinuousRectSearchSpace,Nothing}}) at bboptimize.jl:63
top-level scope at util.jl:234 [inlined]
top-level scope at untitled-ac9baa1509b4e4ac68e7c1d8ef6ff215:0

If you go to opt_controller.jl:362 (BlackBoxOptim\YCrqH\src\opt_controller.jl:362), there is a function write_result, and strftime is not define. strftime only works for julia before 1.0 version. 

function write_result(ctrl::OptRunController, filename = "")
    if isempty(filename)
        timestamp = **strftime**("%y%m%d_%H%M%S", floor(Int, ctrl.start_time))
        filename = "$(timestamp)_$(problem_summary(ctrl.evaluator))_$(name(ctrl.optimizer)).csv"
        filename = replace(replace(filename, r"\s+", "_"), r"/", "_")
    end
    save_fitness_history_to_csv_file(ctrl.evaluator.archive, filename;
            header_prefix = "Problem,Dimension,Optimizer",
            line_prefix = "$(name(problem(ctrl.evaluator))),$(numdims(ctrl.evaluator)),$(name(ctrl.optimizer))",
            bestfitness = opt_value(problem(ctrl.evaluator)))
end

**Comment by robertfeldt** [comment]
Sorry for this. Thanks, I made the simple fix. Please check if latest master branch fixes your problem.
