### ISSUE TITLE
How do I set the mutation rate?

### ISSUE THREAD

**Issue by clintonTE** [robertfeldt/BlackBoxOptim.jl#151]
While I am admittedly unfamiliar with these algorithms, I didn't see how to do this from the examples or tests (though I could easily have missed something). I'm guessing it's possible given all the work around the mutation operator?

**Comment by robertfeldt** [comment]
Sorry for missing your questions earlier. Maybe this is not longer relevant and it depends on which optimizer you want to do this for. The adaptive DE variants don't use mutation but have a change rate parameter which is the probability that the value at one position will be crossed over from the two parents. But this rate (cr) is adapted as the optimization goes on so changing the initial value shouldn't be very important. A bimodal Cauchy distribution is used to sample new cr values as optimization goes on so if you want to try tinkering with it check the `:crdistr` parameter as defined in this file:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/168226787b36b6a5b0ef737fbaeef4588835e3b2/src/adaptive_differential_evolution.jl#L6

The adaptation should make it fairly robust to the choice of distribution though and I haven't played with it myself.
