### ISSUE TITLE
RngSeed not used when RandomizeRngSeed is false

### ISSUE THREAD

**Issue by tomyun** [robertfeldt/BlackBoxOptim.jl#158]
I somehow had an impression that RNG was always reset with `RngSeed` regardless of the status of `RandomizeRngSeed` which would just decide whether to (randomly) change the value of `RngSeed` from its default (1234). After some testing and reviewing the code, it seems not the case since `Random.seed!` would be called only when `RandomizeRngSeed = true`.

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/9ab0e363047c259279d8021d481d7de96cf44b6d/src/opt_controller.jl#L429-L434

As I had an expectation to use `RandomizeRngSeed = false` to easily reproduce optimization results, it'd be nice if BlackBoxOptim could take care of this by having `Random.seed!()` always called in `init_rng!()`.

**Comment by robertfeldt** [comment]
Sorry for slow response. 

Yes, this makes sense to me. Changing this.

**Comment by robertfeldt** [comment]
Please check this commit and try on master branch to ensure this does what you mean:

https://github.com/robertfeldt/BlackBoxOptim.jl/commit/37d1317a62e0a4bc4053b89599f2323c44ae036b

Closing this for now.
