### ISSUE TITLE
SearchRange question

### ISSUE THREAD

**Issue by bienpierre** [robertfeldt/BlackBoxOptim.jl#160]
Hello,

When using: SearchRange  = (-5.0, 5.0) whitin bboptimize. Is the allowing range equals to:

-5.0 < SearchRange < 5.0
or
-5.0 ≤  SearchRange ≤  5.0

I ran several optimization and I can't figure out which one it is.

Regards

**Comment by robertfeldt** [comment]
It's inclusive at both ends, see example code:

```julia
julia> f(x) = (x[1] - 5.0)^2 # optimum at 5.0

julia> res = bboptimize(f; SearchRange = (5.0, 6.0), NumDimensions = 2);

julia> best_candidate(res)[1]
5.0

julia> f2(x) = (x[1] - 6.0)^2 # optimum at 6.0

julia> res2 = bboptimize(f2; SearchRange = (5.0, 6.0), NumDimensions = 2);

julia> best_candidate(res2)[1]
6.0
````

**Comment by bienpierre** [comment]
Thanks.
