### ISSUE TITLE
Restart the optimization while fixing certain parameters

### ISSUE THREAD

**Issue by zxjroger** [robertfeldt/BlackBoxOptim.jl#173]
Hi, I have a question about the restart of the optimization. I am using the "adaptive_de_rand_1_bin_radiuslimited" algorithm. I wonder if it is possible to do the following. Suppose that I have 5 parameters. After the first Julia session, I get the candidate solution for all the 5 parameters. Then, in the second Julia session, I would like to fix the first 2 parameters at the value in the first Julia session, then I only optimize over the remaining 3 parameters. How can I tell the solver that there is a good starting value for the remaining 3 parameters from the previous Julia session? Thank you.

**Comment by Libbum** [comment]
Not possible as yet I believe. See #74.

**Comment by robertfeldt** [comment]
Yes, I will address this soon. Problem is not that it is hard to do, just that different algos implies different internal representations and thus needs to do it slightly differently. But this has been on the todo for long so will prioritize.

**Comment by zxjroger** [comment]
All right, thanks for this amazing package!

**Comment by robertfeldt** [comment]
Latest master branch now have a simple way to give an initial starting point for the search. Feel free to try it out (if `BlackBoxOptim` is still interesting to you). Sorry for the very long delays on this but I'm getting back to the package after a lot of other tasks in recent years.

**Comment by zxjroger** [comment]
Hi Robert, thank you so much for this improvement!

**Comment by robertfeldt** [comment]
Would be great if you can try this and see if it helps your use case. I rarely use this feature myself so would be good with some "real-world" feedback... :)

**Comment by scepeda78** [comment]
I have a model with 30000 parameters of input, and with the startpoint i was able to reduce the search!. I was trying to do it with the borg_moea also, but it seems that it requires other way to config that!

**Comment by robertfeldt** [comment]
borg_moea should work now on master!

**Comment by scepeda78** [comment]
It works! many thanks for the help!!!
