### ISSUE TITLE
Installing BlackBoxOptim causes massive downgrades

### ISSUE THREAD

**Issue by Datseris** [robertfeldt/BlackBoxOptim.jl#179]
![image](https://user-images.githubusercontent.com/19669089/117274308-3cca1400-ae5d-11eb-99a8-46ee3c0be9ee.png)

Please check your Project.toml dependency bounds; This downgraded 3 major packages: SpecialFunctions, Distributions, JSON

**Comment by robertfeldt** [comment]
Yes, please check if this is solved if you install from #master. If so I'll tag master as a release and hopefully this will be solved.

**Comment by Datseris** [comment]
I confirm adding master fixed everything.

**Comment by robertfeldt** [comment]
Please try if your problem is fixed when installing release v0.6.0:
https://github.com/robertfeldt/BlackBoxOptim.jl/releases/tag/v0.6.0
