### ISSUE TITLE
Halt optimization early from callback function

### ISSUE THREAD

**Issue by jpp46** [robertfeldt/BlackBoxOptim.jl#184]
I would like to know if I can halt the optimization early from the callback function. I assume you can halt early based on reaching a specific fitness goal, but if I want to stop based on something other than fitness what should I do?

**Comment by jpp46** [comment]
I am using the BORG MOEA method btw, I would also be okay with halting using the FitnessTarget, if I could do it in this manner. I have 5 objectives, I want to halt when each of the first 4 objectives are below a certain target.

**Comment by robertfeldt** [comment]
Dear Yoshua, yes this can be achieved via the `shutdown!` method in a callback. I added a short example here:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/early_stopping_in_callback.jl

It is single-objective but hopefully you can adapt this method to your use case.

**Comment by robertfeldt** [comment]
Closing this for now. Just re-open if there are additional questions/comments.
