### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [robertfeldt/BlackBoxOptim.jl#191]
The lack of a tag is blocking https://github.com/SciML/DiffEqParamEstim.jl/pull/164

**Comment by longemen3000** [comment]
bump, i need that compat too

**Comment by robertfeldt** [comment]
I've put this in motion now so hopefully done soon:

https://github.com/JuliaRegistries/General/pull/50074

**Comment by robertfeldt** [comment]
Tag is now done. Please check and if there are any dependency problems please get back to me.
