### ISSUE TITLE
Multi-Objective optimization using BlackBoxOptim.jl package: seeking clarification

### ISSUE THREAD

**Issue by dmresearch15** [robertfeldt/BlackBoxOptim.jl#193]
I’m running the example code to optimize fitness_schaffer1(x) = (sum(abs2, x), sum(abs2, x .- 2.0))

I like to figure out the followings:

1.	ParetoFitnessScheme{2}
What 2 represents inside the curly brackets?

2.	pf = pareto_frontier(res)
There are 120-element Vector. Is there any place to change the default value of 120?

3.	Details of 120-element Vector
Like to figure out what they represent.
120-element Vector{BlackBoxOptim.FrontierIndividualWrapper{Tuple{Float64, Float64}, IndexedTupleFitness{2, Float64}}}:
 BlackBoxOptim.FrontierIndividualWrapper{Tuple{Float64, Float64}, IndexedTupleFitness{2, Float64}}(BlackBoxOptim.FrontierIndividual{IndexedTupleFitness{2, Float64}}(IndexedTupleFitness{2, Float64}((0.9980588444521499, 6.076993313826746), 7.075052158278895, (19, 121), 1.1024139914614826), [0.5678841558214585, 0.581514678153916, 0.5808675486809768], 3, 23878, 13, 1.64915418452e9), (0.9980588444521499, 6.076993313826746))

(0.9980588444521499, 6.076993313826746) = (value of fitness function 1, value of fitness function 2)

7.075052158278895 = sum of value of fitness function 1 and value of fitness function 2

(19, 121) =  what they represent

1.1024139914614826 =  what this represents

[0.5678841558214585, 0.581514678153916, 0.5808675486809768] = Candidate values from res or solution vector.

3, 23878, 13, 1.64915418452e9 =  what they represent

(0.9980588444521499, 6.076993313826746) = (value of fitness function 1, value of fitness function 2)

**Comment by robertfeldt** [comment]
Ok, I'll take them in turns...

> 1. ParetoFitnessScheme{2}
> What 2 represents inside the curly brackets?

The number of fitness functions/values. In the example in the readme we had:

fitness_schaffer1(x) = (sum(abs2, x), sum(abs2, x .- 2.0))

which has 2 components. If you have 3 of them you can instead do, for example:

```Julia
fitness_schaffer3(x) = (sum(abs2, x), sum(abs2, x .- 2.0), x[1] - x[2])
res = bboptimize(fitness_schaffer3; Method=:borg_moea,
                   FitnessScheme=ParetoFitnessScheme{3}(is_minimizing=true),
                   SearchRange=(-10.0, 10.0), NumDimensions=4, ϵ=0.05,
                   MaxSteps=20000, TraceInterval=1.0, TraceMode=:verbose);
...
Best candidate found: [0.752643, 1.2129, 1.00667, 1.02012]

Fitness: (4.09164, 4.12228, -0.46026) agg=7.75367
```

**Comment by robertfeldt** [comment]
> 2. pf = pareto_frontier(res)
> There are 120-element Vector. Is there any place to change the default value of 120?

This depends on the specific fitness functions and the problem and how they affect the Pareto Front. So it is not something you can set the value of. For some problems you can get a small front and for others a very large one. For example in my short run of `fitness_schaffer3` above I got:

```Julia
pf = pareto_frontier(res)
length(pf) # value was 31719
# But let's run 10 times more steps:
res2 = bboptimize(fitness_schaffer3; Method=:borg_moea,
                   FitnessScheme=ParetoFitnessScheme{3}(is_minimizing=true),
                   SearchRange=(-10.0, 10.0), NumDimensions=4, ϵ=0.05,
                   MaxSteps=200000, TraceInterval=1.0, TraceMode=:verbose);
length(pareto_frontier(res2)) # value was 42024
```

In general, you can expect that with more fitness functions and/or longer optimisation time the Pareto Front tends to be (much) larger.

**Comment by robertfeldt** [comment]
> 3. Details of 120-element Vector
> Like to figure out what they represent.

There is lots of internal housekeeping to make the internals work, of course. But the key things as a user is that you want to get the fitness values and the values of the decision variables (what is being optimised) and this info you can get like in the example in the README. Example for the res2 run I did for `fitness_schaffer3` above:

```Julia
pf = pareto_frontier(res2)

# Take one solution/individual on the Pareto front:
pf10 = pf[10]

# We can get the values of its decision variables with params:
params10 = params(pf10) # As expected this is a vector of length 4 (since we said NumDimensions=4 above when optimizing)

# We can also get the 3 fitness values like so:
fs10 = fitness(pf10) # Returns a tuple with the 3 fitness values, for my run: (166.2953388275827, 167.7430098165565, -18.05190659354205)

# If we want to look deeper we can also check what kind of fields there is in the returned object (this is a general Julia strategy, not specific to BlackBoxOptim):
julia> fieldnames(typeof(pf10))
(:inner, :fitness)
julia> fieldnames(typeof(pf10.inner))
(:fitness, :params, :tag, :num_fevals, :n_restarts, :timestamp)
```

Yes, the aggregated fitness is by default just a sum. But you can change this by using a different FitnessScheme. However, it doesn't really matter since the internal fitness front will do Pareto comparison based on the raw fitness values returned from your fitness function. So you can actually aggregate in a different way after you have the front. For example, maybe you want to find the solution with the lowest value of 0.5*fitness2 + 0.8*fitness3 but don't care about fitness 1, you can do:

```Julia
myweighting(f) = 0.5*f[2] + 0.8*f[3]
best_myweighting, index = findmin(map(i -> myweighting(fitness(i)), pf))
```

and the best_myweighting value should now be the smallest on the whole front so for example:

```Julia
julia> @show myweighting(fitness(pf[index])) <= myweighting(fitness(pf[index+1]))
myweighting(fitness(pf[index])) <= myweighting(fitness(pf[index + 1])) = true
true

julia> @show myweighting(fitness(pf[index])) <= myweighting(fitness(pf[index-1]))
myweighting(fitness(pf[index])) <= myweighting(fitness(pf[index - 1])) = true
true
```

Hope this helps.

**Comment by dmresearch15** [comment]
Hi Professor Feldt,

Thanks for your response.

The solution has helped me to understand the problem in a logical way.

Once again, thank you very much for the time you've given.

Sincerely
Deb
