### ISSUE TITLE
Hope update compat of HTTP.jl and release

### ISSUE THREAD

**Issue by zsz00** [robertfeldt/BlackBoxOptim.jl#203]

**Comment by zsz00** [comment]
@robertfeldt

**Comment by ianfiske** [comment]
I am hitting version conflict issues related to this as well.  And better yet, does this package really need HTTP.jl as a dependency?  It seems unrelated to optimization.

**Comment by robertfeldt** [comment]
Yes, we should delete this dependency over time. Merging/fixing for now.

**Comment by zsz00** [comment]
can you release?
