### ISSUE TITLE
replace findn(A) with findnz(A)

### ISSUE THREAD

**Issue by stevengj** [robertfeldt/BlackBoxOptim.jl#204]
I noticed that you are still using `findn`, which was deprecated in Julia 0.7 and removed in Julia 1.0: https://github.com/robertfeldt/BlackBoxOptim.jl/blob/83c811671c00fffdcaadf042ad07ee2e2194ecbf/spikes/sparse_cholesky_covar_sampler.jl#L9

Since `A` is a sparse matrix here, maybe you want `findnz`.

(Also, that `broadcast` method seems to be type piracy.)

**Comment by robertfeldt** [comment]
Thanks, this is only a spike (so not part of the actual lib code) but will fix.

**Comment by robertfeldt** [comment]
Ok, should now be fixed:

https://github.com/robertfeldt/BlackBoxOptim.jl/commit/e036bc3120e45344b2c611eaf0fdf7c142038667

I'd rather not get back into this very old code to address the type piracy; this spike is only there to explore different performance trade-offs in one of the algorithms and not part of the lib proper. I'd rather keep this spike as "inspiration" for potential future performance explorations.
