### ISSUE TITLE
how to set the parameters constraints ?

### ISSUE THREAD

**Issue by Siyuan9** [robertfeldt/BlackBoxOptim.jl#205]
when I use BlackBoxOptim.jl to calibrate my model,  I have more than three parameters to calibrate, I give them the same range, but I also have other constraints on them, for example, the first parameter is always larger than the second one, the second one is always larger than the third one, I don't know how to add these constraints into the method when calibrating these parameters, could you please help me?

 res = bboptimize(my_saving_fitness; Method=:borg_moea,
                 FitnessScheme=ParetoFitnessScheme{7}(is_minimizing=true,aggregator=DE),
                 SearchRange=[ (0.0,400.0),(0.0,400.0),(0.0,400.0)],
                 PopulationSize =100,NumDimensions=3,ϵ=0.001,
                 MaxFuncEvals=15000,TraceInterval=1.0,TraceMode=:compact)

**Comment by robertfeldt** [comment]
Thanks for using BBO. There are some examples of optimising with constraints, see for example:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/constrained_problem_with_inequalities.jl

But let me also describe it in general terms:

1. There is no direct support for this in the package itself. 
2. However, often it can be done by adapting your fitness function to penalise when constraints are not fulfilled.
3. The general idea is to state each constraint and then add some large penalty which is larger the further away a solution is from fulfilling the constraint.

I added a concrete example here:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/response_to_questions/constrained_problem_with_larger_than_equalities.jl

You can also do it as a multi-objective problem where the goal is to minimise the original fitness function as well as the inequalities for each constraint. But doing it with penalties is often simpler and faster.

Hope it helps!

**Comment by robertfeldt** [comment]
Closing for now.
