### ISSUE TITLE
Saving Results 

### ISSUE THREAD

**Issue by astro-kevin** [robertfeldt/BlackBoxOptim.jl#212]
How do you save the results from running BlackBoxOptim? I'd like to save the object to disk and then be able to access it in another file.

**Comment by robertfeldt** [comment]
Hmm, can you provide more info on what you want to save? You should be able to use normal Julia Serialization to save specific objects but maybe you mean something more specific.

**Comment by robertfeldt** [comment]
Also check this example and see if it helps you:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/save_and_load_optimization_state_to_disc.jl

**Comment by astro-kevin** [comment]
I see. I was just thinking of a method (like the save method in MCMCchains) that would save a specific object rather than a generic serialization object. I guess serialization would work just fine though.

**Comment by robertfeldt** [comment]
Closing this. If you have further questions, just reopen.
