### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by svilupp** [robertfeldt/BlackBoxOptim.jl#222]
Thank you for this awesome package!

I was wondering if it would be possible to release a new version.

The latest release is holding back a lot of packages that I use, because of StatsBase 0.34.
I see that master (0.6.13) is already compatible with StatsBase 0.34.

Thank you :)

**Comment by svilupp** [comment]
Hi there, just a very tiny nudge asking to tag a new version :-) I've used it a bit and all seems to be working as expected.

Thank you!

**Comment by ven-k** [comment]
Bump on this issue.

**Comment by Datseris** [comment]
@robertfeldt can you please tag a new release of this with StatsBase 0.34 compatibility?

**Comment by robertfeldt** [comment]
Ok, it's happening:

https://github.com/JuliaRegistries/General/pull/97482

Sorry for slow responses on this, have been traveling a lot this year. Hoping to work more on the package starting from this Christmas...
