### ISSUE TITLE
Difficulty Installing BlackBoxOptim on MacOS

### ISSUE THREAD

**Issue by tlorance** [robertfeldt/BlackBoxOptim.jl#224]
I should begin by saying that I am very new to julia, although I am a fairly seasoned coder of python, java, and C.  I would like to use a Julia program that has BlackBoxOptim as a dependency (Clapeyron.jl).  However, when I try to import BlackBoxOptim and julia attempts to install it, I keep getting the error:
`
ERROR: SystemError: opening file "/Users/Project.toml": Permission denied
`
There is no Project.toml file in the folder Users; I believe that the file is where BlackBoxOptim is named as a dependency and there are copies of it in the julia installation of the Clapeyron package, but not in Users.
I have tried installing BlackBoxOptim directly according to the readme on this site.  The standard Pkg.add method throws the same error I was obtaining before.  When I try to use `Pkg.clone("https://github.com/robertfeldt/BlackBoxOptim.jl")`, it throws the error:
`ERROR: UndefVarError: `clone` not defined
`
which is odd because I have used clone before successfully.  I am sure I am either doing something simple incorrectly or that there is a simple solution I don't know; I would appreciate any guidance you can provide.  Thank you.

**Comment by tlorance** [comment]
My apologies: this turns out to be related to the way julia is installed by default on MacOS systems, and the symlinking info found at https://julialang.org/downloads/platform/ solves the problem.

**Comment by robertfeldt** [comment]
Ok, np.
