### ISSUE TITLE
Result type

### ISSUE THREAD

**Issue by matthieugomez** [robertfeldt/BlackBoxOptim.jl#24]
Could bboptimize returns a result of a new type rather than a tuple ?
This is the relevant code from Optim
https://github.com/JuliaOpt/Optim.jl/blob/fe546a68c6034bf8828b10aa2517c1f4db8e5c60/src/types.jl

**Comment by robertfeldt** [comment]
Yes, I think its the right way to go. Let me check the whole design of the top-level interface and we try to make one change that handles several issues. We also want to change how parameters are handled so we don't both have keyword args and a param dict.

**Comment by matthieugomez** [comment]
Great! Thanks

**Comment by robertfeldt** [comment]
@matthieugomez Please check the proposed top-level use cases shown here:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/design/design_by_testcode/test_bboptimize_toplevel_interface.jl

I will have vacation this and the coming week so unfortunately might have longer answer/fix/merge times.

**Comment by matthieugomez** [comment]
From what I understand you're proposing to have
- return a result when the bboptimize is CTRL+C stopped
- allow put the result in the argument of bboptimize
Both would be excellent functionalities

To be honest, I was just thinking of types for these two functionalities 
(i) being able to get a minimizer by a name rather than its position (as currently done)
(ii) pretty printing
Both less ambitious than what you're proposing.

I think that it would be better to mimic the [API of Optim](https://github.com/JuliaOpt/Optim.jl/pull/87) so that users can easily experiment between these packages. So for instance, call the fields/methods
 minimum, minimizer, iterations rather than best, best fitness, numcalls, numruns.

**Comment by robertfeldt** [comment]
I don't know about CTRL+C, nothing about that here. Just that you might want to improve on an opt result in several steps/runs.

MimicingOptim is fine but I don't want BBOptim to become illogical... ;) If I am maximizing rather than minimizing a function I don't want to acces the result with "minimizer"... ;)

**Comment by matthieugomez** [comment]
Oh misread the meaning of optctrl. I think it would be a nice feature though. I think the construction could be something like

```julia
try
   .....
catch ex
    if isa(ex, InterruptException)
        return(currentbestresult)
    end
```

I understand your point about minimizer. I'm just saying you may be able to mimic the parts that work for you. For instance, the number of iterations is given as `iterations` in a lot of packages in JuliaStats. It's a detail but this kind of unified API makes a language nicer to use.

**Comment by robertfeldt** [comment]
Yes, I'll try to stay as close to Optim as I find reasonable.

The try/catch is a good idea as long as it doesn't affect performance. I guess it shouldn't if we do it only at the top-level. Should be fine.

**Comment by robertfeldt** [comment]
A basic result type is now returned in the new top-level interface. It needs a show method etc but it should work as we discussed it and there is some basic Optim API mimicing. Please do a pull request if you want a different interface or want to mimic Optim more. Thanks.
