### ISSUE TITLE
version number/tag

### ISSUE THREAD

**Issue by steven-varga** [robertfeldt/BlackBoxOptim.jl#27]
Hi,
the recent BlackBoxOptim package doesn't seem to have any version numbering/tagging; preventing to pin the package to a stable version.
Would  it be possible to tag the package when API changes, or is it already tagged and I am doing something wrong?

best,
steve
BlackBoxOptim                 0.0.0-             master
julia> versioninfo()
Julia Version 0.4.0-dev+5860
Commit 7fa43ed (2015-07-08 20:57 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.3

**Comment by robertfeldt** [comment]
Yes, I'd like to do this but not sure how. Is it enough if I tag the github repo or do I need to tag from/in Julia?

BlackBoxOptim is only "half-way" an official package if I remember correctly. We have the name but not yet added to official MetaData. I'd like to get the coverage/testing up again before we become official.

**Comment by robertfeldt** [comment]
I have git tagged a v0.5.0 version:

https://github.com/robertfeldt/BlackBoxOptim.jl/releases/tag/v0.5.0

Please tell me if I also should do something specific on the Julia end.

**Comment by robertfeldt** [comment]
And here is a v0.4.0 version with the old top-level interface:

https://github.com/robertfeldt/BlackBoxOptim.jl/releases/tag/v0.4.0

**Comment by steven-varga** [comment]
Thank you, for your help!

I think it is a functional and capable package; in addition to being git tagged BlackBoxOptim could benefit wider audience  by adding it to the official repository.

Were it added as an official package then one can take benefit of Julia Pkg.ckeckout, Pkg.pin, Pkg.free mechanism outlined here:
http://julia.readthedocs.org/en/latest/manual/packages/#checkout-pin-and-free

best,
steve

**Comment by alyst** [comment]
AFAICS `BlackBoxOptim` is already registered in `METADATA.jl`, but no versions are tagged.
As I understand, one needs to `Pkg.publish()` to pull request for updating the global metadata.
Since no versions are tagged, the package, unfortunately, doesn't show up in [Julia packages list](http://pkg.julialang.org/).

**Comment by robertfeldt** [comment]
Do you have a "fresh" link to the process needed for this? Last time I tried there was still some hiccup. We clearly want to fix this asap imho.

**Comment by alyst** [comment]
I think [Tagging and publishing your package](http://julia.readthedocs.org/en/release-0.4/manual/packages/#tagging-and-publishing-your-package) should be up-to-date, but I have never published a package yet.

**Comment by robertfeldt** [comment]
Ok, I think I have done all needed steps so now just waiting for the pull request to be accepted:

https://github.com/JuliaLang/METADATA.jl/pull/3427
