### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by simonp0420** [robertfeldt/BlackBoxOptim.jl#4]
I'm hoping you'll entertain a few feature requests for future versions:

1.  Support for parallel evaluation of objective functions.  In my work a typical objective function evaluation requires several minutes, so speeding up the optimization by parallelization is imperative.  The code I'm porting over from Matlab uses Hansen's cmaes.m as the optimization engine.  When instructed to run in parallel mode, cmaes simply calls my objective function with a list of candidate points, rather than just a single point of the search space.  My code then evaluates the objective functions for the elements in this list in parallel.

2.  An additional stopping criterion:  The existence of a file in the working directory having a particular name, with particular contents on the first line would cause immediate termination of the optimization run.  For example, the file name might be `stop.dat` and the special contents on the first line could be `stop now`. This would allow a user to gracefully exit a long optimization run.  Your package could change the contents of the first line so that a subsequent invocation of the optimizer would run normally without the user having to remember to edit the file.

Thanks,
--Peter

**Comment by robertfeldt** [comment]
This has been partly addressed and there are RFC/WIP PR's that show the parallel evaluation possibilities.
