### ISSUE TITLE
Easier way to use ftol

### ISSUE THREAD

**Issue by matthieugomez** [robertfeldt/BlackBoxOptim.jl#49]
I'm using BlackBoxOptim to solve a set of non linear equalities. I'd like to ensure that BlackBoxOptim runs until the solution of the system is found with a certain tolerance. Would it be possible to do that using the exported API? For now, I think I need to define a `bbsolve` function
```
function bbsolve(func, parameters::BlackBoxOptim.Parameters = BlackBoxOptim.EMPTY_PARAMS; kwargs...)
	parameters = chain(convert(ParamsDict, parameters), convert(ParamsDict, kwargs))
	params = chain(BlackBoxOptim.DefaultParameters, parameters)
	ss = BlackBoxOptim.check_and_create_search_space(parameters)
	problem = FunctionBasedProblem(func, "<unknown>", params[:FitnessScheme], ss, 0.0)
 	optimizer_func = chain(BlackBoxOptim.SingleObjectiveMethods, BlackBoxOptim.MultiObjectiveMethods)[params[:Method]]
	optimizer = optimizer_func(problem, params)
	ctrl = BlackBoxOptim.OptController(optimizer, problem, params)
	BlackBoxOptim.run!(ctrl)
end
```

**Comment by matthieugomez** [comment]
I think a solution would be to change [l31](https://github.com/robertfeldt/BlackBoxOptim.jl/blob/4dd9ec2d6a470c68647ce7cf821ded623c6184cc/src/bboptimize.jl#L31) to 
```julia
    problem = FunctionBasedProblem(func, "<unknown>", params[:FitnessScheme], ss, params[:OptimizationValue])
```

**Comment by robertfeldt** [comment]
There are many ways to use tolerance in optimization and I think you are right that we may not cover all of them in a good way in BBO currently. But I need to understand better what you need to achieve. Have you tried setting the `MinDeltaFitnessTolerance` parameter as a normal parameter to `bbsetup` or `bboptimize`? The argument to `FunctionBasedProblem` is a known optimum of a function if one is known so does not sound like what you need. You can of course also try other ways of extending the run time of the optimizations using the number of steps or max time.

**Comment by robertfeldt** [comment]
Or do you mean that you actually know the optimum value? Then I agree we might need a way to set it via parameters. For now you can just copy and make your own version of `bbsetup` as you indicate, yes.
