### ISSUE TITLE
examples are outdated

### ISSUE THREAD

**Issue by AStupidBear** [robertfeldt/BlackBoxOptim.jl#57]
I want to use  restarting_optimization.jl  in the example directory. But they are not compatible with the current version of this package.

**Comment by robertfeldt** [comment]
Sorry about this. Will fix right away. There are probably more examples that are outdated; please report if you find anything strange and we'll fix it.

**Comment by robertfeldt** [comment]
Ok, now fixed here on git so please clone to make sure you have latest.
