### ISSUE TITLE
Make BlackBoxOptim compatible with Julia 0.5 and above

### ISSUE THREAD

**Issue by Ayush-iitkgp** [robertfeldt/BlackBoxOptim.jl#63]
Hello,
We want to provide support of BlackBoxOptim for global optimization in [DiffEqParamEstim.jl](https://github.com/JuliaDiffEq/DiffEqParamEstim.jl). But it is throwing lots of warnings in Julia 0.5 and also the error for 30 dimension Rosenbrock function (ERROR: MethodError: no method matching calculate_evol_path_params(::Int32, ::Array{Float64,1})). Is there any possibility of making it compatible for Julia v0.5 and above?

cc - @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
Last tag was in July. Did you try checking out master?

**Comment by Ayush-iitkgp** [comment]
`Pkg.status("BlackBoxOptim")
` 
BlackBoxOptim                 0.2.1+             master
The above error persists but the warnings are gone.

**Comment by ChrisRackauckas** [comment]
Are you on 32-bit Windows? This package seems to have mistakenly used `Int64` like Optim did...

**Comment by ChrisRackauckas** [comment]
Try my branch. https://github.com/robertfeldt/BlackBoxOptim.jl/pull/64 . It fixes the 32-bit issues.

**Comment by robertfeldt** [comment]
I just tagged a new version so should soon be merged on main METADATA, hopefully. I'd like to step up and extend BlackBoxOptim again so please keep any ideas and code/PR's coming. Thanks for your interest.
