### ISSUE TITLE
MethodError: no method matching start(::BlackBoxOptim.OptimizationResults)

### ISSUE THREAD

**Issue by finmod** [robertfeldt/BlackBoxOptim.jl#66]
Trying to run all the examples, high_dimensional_rosenbrock.jl and some others that were not modified last week throw the following error:

fitness_for_opt(problemname, 2, 10, 100, :adaptive_de_rand_1_bin)

Rosenbrock, n = 2, optimizer = adaptive_de_rand_1_bin
Starting optimization with optimizer BlackBoxOptim.DiffEvoOpt{BlackBoxOptim.FitPopulation{Float64},BlackBoxOptim.RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},BlackBoxOptim.RandomBound{BlackBoxOptim.RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps

Optimization stopped after 101 steps and 0.0009999275207519531 seconds
Termination reason: Max number of steps (100) reached
Steps per second = 101007.32093466858
Function evals per second = 130009.42298521698
Improvements/step = 0.36
Total function evaluations = 130

Best candidate found: [-2.78048,7.65913]

Fitness: 14.809475789

MethodError: no method matching start(::BlackBoxOptim.OptimizationResults)
Closest candidates are:
  start(::SimpleVector) at essentials.jl:170
  start(::Base.MethodList) at reflection.jl:258
  start(::IntSet) at intset.jl:184
  ...

 in fitness_for_opt(::String, ::Int64, ::Int64, ::Int64, ::Symbol) at .\In[2]:8

And the next line:

for (dims, steps) in [(128, 1e6), (256, 2e6), (512, 4e6)]
  println("Num dims = ", dims, ", Num steps = ", steps)
  fitness = fitness_for_opt(problemname, dims, 50, steps, :adaptive_de_rand_1_bin)
end

Num dims = 128, Num steps = 1.0e6

Rosenbrock, n = 128, optimizer = adaptive_de_rand_1_bin
Starting optimization with optimizer BlackBoxOptim.DiffEvoOpt{BlackBoxOptim.FitPopulation{Float64},BlackBoxOptim.RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},BlackBoxOptim.RandomBound{BlackBoxOptim.RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps
0.50 secs, 64308 evals, 64202 steps, improv/step: 0.174 (last = 0.1741), fitness=2442.363745254
1.00 secs, 125149 evals, 125044 steps, improv/step: 0.176 (last = 0.1788), fitness=412.429653553
1.50 secs, 185556 evals, 185457 steps, improv/step: 0.181 (last = 0.1906), fitness=318.203482602
2.00 secs, 250841 evals, 250747 steps, improv/step: 0.182 (last = 0.1840), fitness=313.772299580
2.51 secs, 322866 evals, 322775 steps, improv/step: 0.183 (last = 0.1872), fitness=311.988327655
3.01 secs, 387349 evals, 387261 steps, improv/step: 0.183 (last = 0.1840), fitness=310.106016270
3.51 secs, 456980 evals, 456895 steps, improv/step: 0.185 (last = 0.1943), fitness=286.289713893
4.01 secs, 529895 evals, 529812 steps, improv/step: 0.184 (last = 0.1818), fitness=239.909922582
4.51 secs, 604067 evals, 603990 steps, improv/step: 0.185 (last = 0.1872), fitness=172.293105809
5.01 secs, 669166 evals, 669092 steps, improv/step: 0.186 (last = 0.1925), fitness=159.858206148
5.51 secs, 738414 evals, 738345 steps, improv/step: 0.185 (last = 0.1851), fitness=104.056642604
6.01 secs, 811251 evals, 811185 steps, improv/step: 0.185 (last = 0.1846), fitness=102.906458438
6.51 secs, 875571 evals, 875507 steps, improv/step: 0.185 (last = 0.1865), fitness=101.486934244
7.02 secs, 945691 evals, 945630 steps, improv/step: 0.186 (last = 0.1913), fitness=100.566451284

Optimization stopped after 1000001 steps and 7.42300009727478 seconds
Termination reason: Max number of steps (1000000) reached
Steps per second = 134716.55488286095
Function evals per second = 134724.50315165074
Improvements/step = 0.186081
Total function evaluations = 1000060

Best candidate found: [0.999778,0.999393,0.999552,1.0012,1.00109,1.00006,1.00102,1.00077,0.999943,1.00044,1.00014,0.999701,0.999263,1.00038,1.00085,1.00081,1.00108,0.999933,0.999358,1.0001,1.00049,1.00019,1.00014,1.00014,1.00052,1.00036,0.999297,0.999253,1.00031,1.00052,1.00007,0.999845,1.00015,0.999746,1.00027,1.00116,0.999125,0.99844,1.00011,0.999508,0.999093,0.999971,0.9983,0.998624,0.999006,0.999172,1.00071,1.00038,0.999396,0.999204,0.999713,0.99944,0.99863,0.998816,0.999312,0.999532,1.00013,0.99914,0.998135,0.996522,0.996164,0.992173,0.981551,0.962452,0.933084,0.871296,0.765644,0.597394,0.368063,0.142401,0.0278034,0.0111991,0.00811688,0.0122003,0.00899323,0.00968402,0.0101368,0.00984478,0.0115218,0.00968908,0.00847069,0.0106596,0.0107605,0.0106498,0.00781984,0.0106147,0.00428776,-0.316451,0.620049,0.800388,0.898521,0.948649,0.973744,0.987115,0.99399,0.996537,0.998642,1.00033,0.998881,0.999249,0.998546,0.997564,0.9964,0.991797,0.98334,0.967661,0.941945,0.891133,0.804099,0.653335,0.434981,0.199469,0.0473854,0.0125062,0.00962304,0.0102804,0.0100706,0.010631,0.00931846,0.0109869,0.00989174,0.00902658,0.0102114,0.0101546,0.00885919,0.0105129,0.010692,0.000286411]

Fitness: 99.828907853

MethodError: no method matching start(::BlackBoxOptim.OptimizationResults)
Closest candidates are:
  start(::SimpleVector) at essentials.jl:170
  start(::Base.MethodList) at reflection.jl:258
  start(::IntSet) at intset.jl:184
  ...

 in fitness_for_opt(::String, ::Int64, ::Int64, ::Float64, ::Symbol) at .\In[2]:8
 in macro expansion; at .\In[7]:3 [inlined]
 in anonymous at .\<missing>:?

**Comment by robertfeldt** [comment]
Thanks for this. Yes, there are some problems with the example code having gone out-of-date with the rest of the package. Will check this soon.

**Comment by robertfeldt** [comment]
Latest master has fixed this problem. Sorry it took some time but wanted to look at use on julia 0.6 first...
