### ISSUE TITLE
Direct Multiple shooting method in BlackBoxOptim

### ISSUE THREAD

**Issue by finmod** [robertfeldt/BlackBoxOptim.jl#67]
@robertfeldt  Any use of BlackBoxOptim for the direct multiple shooting method for IVP of ODEs?

**Comment by robertfeldt** [comment]
Sorry, but I do not know what this is. Can you elaborate?

**Comment by finmod** [comment]
Here is some doc: http://casadi.sourceforge.net/v3.1.0/users_guide/html/node8.html also documented there: https://en.wikipedia.org/wiki/Direct_multiple_shooting_method and https://en.wikipedia.org/wiki/Parareal .

**Comment by robertfeldt** [comment]
Hmm, not sure I have enough experience with this to judge if a BBO solution is feasible or efficient. Why not try to implement it? In general, for any problem, if there are already existing, specialized solution methods they can often be better than a general one. OTOH, they often "break down" if one takes a step away from their specific area of "expertise". So it might be worth trying. If you code it up and run into any particular problems feel free to get back to me and I'll see if I can find any improvements.
