### ISSUE TITLE
Restart optimization

### ISSUE THREAD

**Issue by jbrea** [robertfeldt/BlackBoxOptim.jl#72]
Thanks for this nice and useful package!

I was trying to continue an optimization problem (with saving to disk) but failed to understand how to do that. Following one of the examples I tried the following, with the surprising result of a non-monotonic fitness. Is this a bug or did I misunderstand something?

```julia
julia> using BlackBoxOptim

julia> function rosenbrock2d(x)
         return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
       end
rosenbrock2d (generic function with 1 method)

julia> opt = bbsetup(rosenbrock2d; SearchRange = (-5.0, 5.0), NumDimensions = 2,
              MaxSteps = 10, TraceMode = :silent);

julia> res = [bboptimize(opt) for _ in 1:10];

julia> println("Fitness progress: ", map(best_fitness, res))
Fitness progress: [2.60211, 350.808, 33.158, 7.12917, 13.7697, 57.5527, 5.39775, 21.7929, 2.10093, 2.10093]

julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-4.0.0 (ORCJIT, broadwell)

julia> Pkg.status("BlackBoxOptim")
 - BlackBoxOptim                 0.3.0
```

**Comment by robertfeldt** [comment]
Thanks for the nice words and sorry for this. It does look like a bug. I don't think we've seen this on 0.5 before. Let me investigate.

**Comment by robertfeldt** [comment]
No, doesn't seem to have to do with the Julia version but with the low number of steps. When I increase MaxSteps to 1000 I don't seem to have the problem and get a nice monotonically decreasing sequence. So might be some problem with the "probability of mixing", i.e. when number of steps is low enough that not all individuals in a population are "touched". Still, it might be considered a bug so I will investigate more later. If you find problems when you go for longer optimization times / more steps please give further details. Cheers.

**Comment by robertfeldt** [comment]
Ok, bug was that for each new bboptimize call a new archive was created (the archive keeps the top results) so even if the population was the same (and still contained monotonically decreasing "best" candidate solution) each new archive did not have enough time to bump into that best individual and keep it at the top of the archive toplist. This always happened only for short step lengths which are rarely used for harder problems and thus we had not ran into it.

Thanks for helping us find this. Fix coming shortly.

**Comment by robertfeldt** [comment]
Ok, this commit should now have fixed this, added a testset for it as well as updated the save/load example to be up-to-date with the interface. See:

https://github.com/robertfeldt/BlackBoxOptim.jl/commit/13d9f0e54ce026aefface6bf0518881a93c5781d

for details. Thanks again.

**Comment by jbrea** [comment]
Awesome! Thanks much for fixing this so quickly!
