### ISSUE TITLE
README example errors

### ISSUE THREAD

**Issue by BeastyBlacksmith** [robertfeldt/BlackBoxOptim.jl#77]
Running this example from the README
```jl
function rosenbrock(x)
  return( sum( 100*( x[2:end] - x[1:end-1].^2 ).^2 + ( x[1:end-1] - 1 ).^2 ) )
end

res = compare_optimizers(rosenbrock; SearchRange = (-5.0, 5.0), NumDimensions = 30, MaxTime = 3.0);
```
Terminates with `KeyError: key: :TraceMode not found`.

**Comment by robertfeldt** [comment]
That's embarassing. What version of Julia are you on? (To help me track this down)

**Comment by BeastyBlacksmith** [comment]
0.6.2

**Comment by robertfeldt** [comment]
Ok, I can replicate so should be easy fix. I'm out for a couple of hours though but will investigate tonight. It is a bit strange since we have the README examples also in the test suite and the suite passes but will investigate...

**Comment by robertfeldt** [comment]
Ah, this has already been fixed in the master branch. I'll try to commit a new version to metadata based on the master branch soon. If you are eager please run from the master branch for now.

**Comment by BeastyBlacksmith** [comment]
Ok, thanks for looking at it!
