### ISSUE TITLE
PSO

### ISSUE THREAD

**Issue by phelipe** [robertfeldt/BlackBoxOptim.jl#81]
Is there a particle swarm optimization?

**Comment by robertfeldt** [comment]
We have done some spikes but there is no complete one in there yet. Do you have some specific experience showing them being better than Differential Evolution (DE)? I've often found particle swarms and DE performing on par with each other.

**Comment by phelipe** [comment]
Sorry for the delay. I read somewhere that PSO was implemented in this package, so I asked. Thanks!
