### ISSUE TITLE
Efficient Pareto frontier

### ISSUE THREAD

**Issue by alyst** [robertfeldt/BlackBoxOptim.jl#82]
At the moment `EpsBoxArchive` type implementing Pareto frontier stores it as a simple `Vector{}`-based container with `O(M)` linear search.
Once the number of points (especially for N-objective problems) gets considerable (~5000), the overhead of maintaining the frontier (checking if candidate solution is dominated by the solutions from the frontier/removing frontier points dominated by the new candidate) becomes too high. Moreover, since the frontier is not parallelized, it becomes a real bottleneck for parallel BBO optimization.

For 2-objective problems we can solve the issue by sorting the solutions using the 1st component.
For N>2 objective problems we need something more advanced.
Without doing much research on the state-of-the-art containers for Pareto frontiers, the obvious candidate is [_k_-d tree](https://en.wikipedia.org/wiki/K-d_tree) (maybe it's even possible to use (N-1)-dimensional k-d trees as the frontier should be (N-1) manifold). [NearestNeighbours.jl](https://github.com/KristofferC/NearestNeighbors.jl) implements k-d trees, but these are the static ones; also I'm not sure whether it implements the range searches we need.

**Comment by robertfeldt** [comment]
Yes, I've also been thinking about this. The Bkd-tree might be a good alternative:

https://klevas.mif.vu.lt/~algis/DSA/bkdtree.pdf

but I also have a half-ready implementation of Boundary Trees/Forest that might be useful:

http://www.aaai.org/ocs/index.php/AAAI/AAAI15/paper/download/9848/9953

I suggest we implement/release one or both of those as separate packages and then use it in BlackBoxOptim.

There are many alternatives though, some kind of location-sensitive hash might also be quite efficient.

**Comment by robertfeldt** [comment]
Please tell me if you go ahead with any of these options so we don't overlap efforts. I think long-term, the multi-objective optimization can be a real "killer app" for BBO so would be nice to really work on these aspects as well as parallellization. Maybe we can aim to release these things quite quickly after Julia 1.0 is out?

**Comment by robertfeldt** [comment]
Some relevant inspiration might be found here:

https://github.com/Keno/LSH.jl

but it seems it is not dynamic but requires the data upfront.

**Comment by robertfeldt** [comment]
Seems his code is general enough that we could quite easily make a more dynamic version though. The functions and types to create the hash functions do not seem to require the data upfront. This is from a cursory look at his code only, though.

**Comment by robertfeldt** [comment]
Downside with LSH is that it typically only provides approximate NN search. I doubt it will make much difference in practice though for our use case. But BKD-trees etc might be more efficient in the medium-sized problems we are likely to have and more straightforward.

**Comment by alyst** [comment]
Bkd-trees look interesting! We would need (-∞, a_1]×...×(-∞, a_n] and (a_1, +∞]×...×(a_n, +∞] range searches to guarantee that at each iteration EpsBoxArchive doesn't contain dominated solutions. Is it possible to implement something equivalent to these range searches on top of LSH or BT?
I'm not sure I will have time to embark on this issue in the coming weeks, but I am very interested in testing WIP implementation(s) for my use cases.

**Comment by robertfeldt** [comment]
I doubt it for LSH but should be possible for BT; not sure about complexity of it though. Maybe bkd-trees is the more traditional choice.

**Comment by robertfeldt** [comment]
Just noting that PH-Trees might also be worth investigating:

https://github.com/tzaeschke/phtree/blob/master/PhTreeRevisited.pdf

**Comment by alyst** [comment]
There's also [RegionTrees.jl](https://github.com/rdeits/RegionTrees.jl). I'm not sure it ideally fits our use case, though.

**Comment by robertfeldt** [comment]
Should be ok for now given the latest merges.
