### ISSUE TITLE
No length method for DictChain

### ISSUE THREAD

**Issue by grahamas** [robertfeldt/BlackBoxOptim.jl#85]
Trying to use JLD to save the results directly gives this error.

I'm making a pull request where I just define the length of a DictChain as the length of its vector. I'm assuming it was only omitted because it wasn't needed, but is there anything I'm missing?

**Comment by robertfeldt** [comment]
No, this sounds safe to add. PR appreciated. :)

**Comment by grahamas** [comment]
Use JLD2 (cf #86)
