### ISSUE TITLE
Upgrade to julia 0.7

### ISSUE THREAD

**Issue by jmgnve** [robertfeldt/BlackBoxOptim.jl#87]
It would be good to upgrade this package to the latest julia version. I have quickly tested to upgrade it automatically with femtocleaner using this recipy:

https://discourse.julialang.org/t/ann-introducing-upgradathon-fridays/12047

Many of the tests still fail after this update. Should I make a pull request with the femtocleaner stuff even though manual adjustments are needed afterwards, or what is the best thing to do for upgrading this package?

**Comment by robertfeldt** [comment]
Thanks for your efforts! Yes, doing a PR and we can see how much work it would be to try to make this pass. I currently have not used 0.7 very much so not clear on the number of changes needed.

**Comment by jmgnve** [comment]
I have used femtocleaner and you find the result of that process here:

https://github.com/jmgnve/BlackBoxOptim.jl/tree/julia07fixes

I am not sure whether I should open a pull request directly on your master branch since the package does not work on v0.7 without additional manual changes.

I have not worked much with others using git. What is the next step workflow wise? I will see if I can find out what breaks the package, and see if I can find fixes. But I probably need some help.

**Comment by robertfeldt** [comment]
Thanks for this. Yeah, maybe make a few small tries on your branch first to see what kind of manual edits would be needed. I'm a bit concerned if this will require us to drop 0.6 support. Does femtocleaner use Compat in a way that we can support both 0.6 and 0.7?

**Comment by jmgnve** [comment]
I have too little experience with compatability issues. See comment in this [thread](https://discourse.julialang.org/t/ann-introducing-upgradathon-fridays/12047/2) by Fredrik Ekre:

_"First off, the process will be much simpler if you choose to drop support for Julia 0.6 on the master branch. Unless you have strong reason to create another release compatible with Julia 0.6 I would strongly recommend doing this, several packages, like StaticArrays and DataStructures, have already done so. If you need to release a 0.6 compatible bugfix release of your package you can do this from a branch later."_

I don´t know whether femtocleaner uses compat, which I´ve never used. I naivly think this is the time to bite in the "sura äpplet" and update all code to the new version, and never look back :). Do you need new versions of bbo for other projects using v6 that are hard to update?

**Comment by robertfeldt** [comment]
Ok, let's aim to go 0.7 only on master then. Should be fine with me unless @alyst has any objections?

**Comment by alyst** [comment]
+1 to branch off `julia_0_6` and convert `master` to 0.7 (the Julia core team is still actively fixing regressions, so there might be a few glitches, but the 0.7 Base and StdLib APIs should be stable now).

There's [femtocleaner bot](https://github.com/apps/femtocleaner/), maybe it makes sense to enable it on this repo to handle this and any future Julia upgrades [semi]automatically?

**Comment by jmgnve** [comment]
I have opened a pull request with the femtocleaner changes.

It seems as if the introduction of named tuples breaks [bboptimize and kwargs2dict](https://github.com/robertfeldt/BlackBoxOptim.jl/blob/1c06731394fee3539db233501236ee02fef101fc/src/bboptimize.jl#L61).

From NEWS.md:

_Keyword argument containers (kw in f(; kw...)) are now based on named tuples. Dictionary functions like haskey and indexing can be used on them, and name-value pairs can be iterated using pairs(kw). kw can no longer contain multiple entries for the same argument name (#4916)._

I don´t yet really understand how that stuff works though.

**Comment by robertfeldt** [comment]
Fixed by latest PR merge.
