### ISSUE TITLE
Feature request: intermittently calling external function.

### ISSUE THREAD

**Issue by korsbo** [robertfeldt/BlackBoxOptim.jl#88]
Hi,

I often find myself monitoring the fitness value during an optimisation, wondering if I have finally found something good enough. The problem is that it can be difficult to judge success by this number. One thing which I would have liked to do is to intermittently use the best parameter set to update some plot or other visualisation. 

Currently, the opt can call a printout function every once in a while. But if we could add a feature to intermittently call a user-defined function with the parameters as arguments, then one could monitor progress in whatever way one sees fit.

**Comment by robertfeldt** [comment]
Thanks for the proposal. Yes, there has been a previous feature request along these lines so I think it is time to add it as an option. What about an interface like this:

We add two options with names and default options like so:

FitnessCallback = nothing
CallbackFrequency = 0

which are used like this:
If the FitnessCallback option is not nothing but a Function it will be called with with frequency CallbackFrequency where the frequency is "approximately" measured as the number of optimization steps (or evaluations? Hmm, might depend on the solver/OptAlg). If the value is below 1 the callback is never called, if it is 1 it is called every step/eval, if it is 100 it is called every 100 steps/evals etc.

The callback will get some kind of argument passed along from which the current best solution and/or fitness can be found but will have to see which internal structure to reuse for this so as not to "cost" performance.

Ok? Comments?

**Comment by korsbo** [comment]
Excellent, I will check this out when I get back to work tomorrow.
Cheers!

**Comment by robertfeldt** [comment]
Have you had a chance to try it @korsbo ? Thanks.

**Comment by korsbo** [comment]
Hi, 
I'm sorry that I have not given feedback yet. I just found out that I'm moving house within a week, so I have not had time to look in to this. I'm hoping that I will have time for this during the afternoon, but I'm afraid that I can make no promises.

**Comment by korsbo** [comment]
I just tried it using:

```julia
] add BlackBoxOptim#master
using BlackBoxOptim
bboptimize(x-> begin sleep(0.01); 1.0 end; 
    MaxSteps=1000, 
    NumDimensions=5,
    FitnessCallback = x->println("hello"),
    CallbackInterval = 1.5,
)

Starting optimization with optimizer DiffEvoOpt{FitPopulation{Float64},RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},RandomBound{RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps
0.52 secs, 47 evals, 26 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000
1.03 secs, 92 evals, 56 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000
1.53 secs, 137 evals, 95 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000
2.04 secs, 179 evals, 132 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000
2.55 secs, 224 evals, 175 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000
```

I expected it to greet me nicely every 1.5 seconds, but it did not. Is my syntax off? `display("hello")` was equally unsuccessful.

**Comment by robertfeldt** [comment]
Sorry, but I renamed it to CallbackFunction:

````
julia> using BlackBoxOptim

julia> bboptimize(x-> begin sleep(0.01); 1.0 end;
           MaxSteps=100,
           NumDimensions=5,
                  CallbackFunction = x->println("hello"),
                  CallbackInterval = 1.5,
              )
Starting optimization with optimizer DiffEvoOpt{FitPopulation{Float64},RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},RandomBound{RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps
hello
0.50 secs, 40 evals, 22 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000
1.03 secs, 81 evals, 49 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000
hello
1.54 secs, 122 evals, 79 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000

Optimization stopped after 101 steps and 1.8488738536834717 seconds
Termination reason: Max number of steps (100) reached
...
```

**Comment by robertfeldt** [comment]
Or even:
````
julia> bboptimize(x-> begin sleep(0.01); 1.0 end;
           MaxSteps=100,
           NumDimensions=5,
                  CallbackFunction = x->println("Fitness = $(best_fitness(x)), $(best_candidate(x))"),
                  CallbackInterval = 1.5,
              )
Starting optimization with optimizer DiffEvoOpt{FitPopulation{Float64},RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},RandomBound{RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps
Fitness = 1.0, [-0.803237, 0.456448, -0.71025, -0.408382, 0.763994]
0.51 secs, 32 evals, 17 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000
1.02 secs, 73 evals, 44 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000
1.53 secs, 114 evals, 75 steps, improv/step: 1.000 (last = 1.0000), fitness=1.000000000
Fitness = 1.0, [-0.710127, 0.871785, 0.490498, 0.169203, -0.762397]
````

**Comment by robertfeldt** [comment]
Closing this since it seems to work on my end and I've heard no complaints about it yet... :)
