### ISSUE TITLE
New release for 0.7?

### ISSUE THREAD

**Issue by Vaibhavdixit02** [robertfeldt/BlackBoxOptim.jl#92]
Hey can you tag a new release for 0.7? From the PR history it looks like the repo has been updated to be 0.7 compatible? I am working on updating a package that has BlackBoxOptim.jl as a dependency and it would make my job a bit easier 🙂 

Thanks!

**Comment by robertfeldt** [comment]
Yes, I aim to do this ASAP but still not fully clear to me if we must add a the manifest.toml etc files that is used in 0.7 and 1.0 Pkg. And if so how to generate the required UUID's etc. If anyone has info on this, please share.

**Comment by korsbo** [comment]
You don't have to do any of that. Just submit a release like normal. 

At some point in the future, this may be changed for you automatically and you will be notified.

**Comment by korsbo** [comment]
I found a reference to back up my claim [here](https://discourse.julialang.org/t/pkg3-plan-and-status/9763).

**Comment by Vaibhavdixit02** [comment]
Yes afaik you don't need to do any of this yet, just have the package be passing the tests in 0.7.

**Comment by robertfeldt** [comment]
Yes, thanks to you both. New 0.4.0 release is tagged and attobot has created a PR so hopefully this is soon ok:

````
https://github.com/JuliaLang/METADATA.jl/pull/16937
````

Please get back to me if there is something missing. Things works on 0.7 on my end but I'm not fully up-to-date with the new Pkg3 system in Julia so I might be missing something.

**Comment by Vaibhavdixit02** [comment]
Thanks for the quick response! I'll go ahead and close this issue now. I did use your master branch for running tests locally and wasn't a problem so I don't expect anything to be missing but let's see. 🙂
