### ISSUE TITLE
Differential Evolution optimizers take a long time to "finalize"

### ISSUE THREAD

**Issue by karajan9** [robertfeldt/BlackBoxOptim.jl#97]
I have encountered the following problem: if I optimize my problem with a variation of a differential evolution algorithm, after it has finished (MaxTime = 60 sec has run out) it takes a long time (~20 min?) until the command is actually finished. There is no more output (the final solution was already printed) but Julia is still busy and using the CPU.

- I am using a more or less fresh Julia 0.7 installation in Juno on Windows 7 with BlackBoxOptim on master.
- I encountered this with de_rand_1_bin and adaptive_de_rand_1_bin_radiuslimited.
- The generated solutions are fine.
- Any of the other algorithms that I tested (*-nes, generating_set_search, probabilistic_descent, resampling_memetic_search, SPSA) don't show this behavior.
- I wasn't able to reproduce this problem on a different machine using the standard rosenbrock function.

Unfortunately the problem occurred on my work computer where I (currently) don't have access to my github account to provide more details right off the bat. If it helps I can try to provide the (lengthy) code that produced this problem. Hopefully the description is enough to give a hint, but I will try to assist to the best of my abilities although I'm not sure how far I can help in terms of debugging.

**Comment by robertfeldt** [comment]
Very interesting. Do you mean that it prints the result but it takes time after that to actually return?

We would really like more details and, preferably, example code to replicate this. Sounds like it could have to do with population-based algorithms but not clear. Do you remember if you used a very large population size? Please try to shorten your example code so you can share it and we can try to dig deeper. This is definitely something we want to fix asap, if possible.

**Comment by robertfeldt** [comment]
Hmm, I tried running a few different DE variants on many-dimensional rosenbrock problems and varied the population size but I cannot replicate what you describe. Please provide example code. Could this somehow be Windows-related? Any chance you can try if it is the same with Julia 1.0?

**Comment by karajan9** [comment]
> Very interesting. Do you mean that it prints the result but it takes time after that to actually return?

Precisely that. With the other methods it returns immediately after printing the final solution, as one would expect.

> Do you remember if you used a very large population size?

I didn't change any of the options for any of the methods, just the MaxTime, SearchRange and possibly NumDimensions, if that is what you mean?

> Any chance you can try if it is the same with Julia 1.0?

I guess that should be no problem, as long as there is no problem with other packages supporting 0.7 but not 1.0 (for whatever reason).

Since this is code I wrote for work I think I will need to ask if I can invest some time to dig into the problem or if it's okay to take the code home to work on it in my free time/test on a Linux machine/publish here. I should get an answer to these questions on Monday.

Just some more info
- I have like 4 or 5 nested functions to calculate a cost value.
- There don't seem to be type problems, my code runs quite fast, considering the amount of calculations necessary.
- I pass around a Struct with some values a lot.
- I calculate rotations with StaticArrays.
- I do a lot of root-finding with the Roots package.
- The cost function can return Inf (I think that's in my latest version?) if the solution is particularly bad, but all algorithms do find a solution using "real" cost values.

**Comment by karajan9** [comment]
After being able to test the issue a bit more thoroughly today, it seems the problem is with Juno, not with BlackBoxOptim. If I include my script in a normal Julia session, everything runs fine; if @time or @elapsed macros are used in Juno they always show the MaxTime, and Julia rattles on after that.

If you have any idea what might cause this, this information could be passed on to the Juno team.
Some rough stopwatching (since the @time macros won't work) seemed to suggest that the correlation between MaxTime and additional time spent is quadratic, if that helps.

**Comment by robertfeldt** [comment]
Sorry, but us hard to know since I don't use Juno. It sounds like it should be related to the population size so you can try increasing that and see if the times increase. Maybe some kind of cleanup or visualisation-related issue in Juno for the matrix used to store the population? You could also try another population-based optimizer, for example Borg MOEA, and see if it seems to be the same problems.
