### ISSUE TITLE
Pass other arguments to optimize function

### ISSUE THREAD

**Issue by bisraelsen** [robertfeldt/BlackBoxOptim.jl#98]
Hopefully I'm not asking an already-answered question.

How can I pass other static (i.e. not optimized) parameters to the function that `bboptimize` operates on?

**Comment by ngiann** [comment]
The documentation for package Optim gives one solution that you can also
use for BlsckBoxOptim:

http://julianlsolvers.github.io/Optim.jl/stable/#user/tipsandtricks/

Hope that helps.

Brett <notifications@github.com> schrieb am Mi., 19. Sep. 2018, 01:05:

**Comment by robertfeldt** [comment]
Yes, the basic idea is to "wrap" the function you really want to optimize (the "original" func) and then unpack the vector from BBO in the wrapper, add any constants or other things you need to add and then call the "original" function. This is much more general than adding a specific interface for all different types of "keeping things constant" and, in general, a very complex process might be needed to go from the vector to a fitness value (think that the vector from BBO is used to setup a simulation which requires many config params and a long execution time before returning a "fitness" value).

Hope this helps.
